#!/usr/bin/env python3
"""Translate SVG labels into Korean while preserving the original artwork."""

import html
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parent.parent
DEST = ROOT / "book-ko" / "images"
ENGLISH = ROOT / "book-en" / "images"
ORIGINAL = ROOT / "book" / "images"

TRANSLATIONS = {
    "fig2-1.svg": {
        "System Prompt": "시스템 프롬프트",
        "&quot;You are a helpful assistant. You MUST answer concisely.&quot;": "&quot;당신은 유용한 AI 비서입니다. 반드시 간결하게 답하세요.&quot;",
        "&quot;Use tools when the user asks for real-time information.&quot;": "&quot;사용자가 실시간 정보를 요청하면 도구를 사용하세요.&quot;",
        "Tool Definitions": "도구 정의",
        "{&quot;name&quot;: &quot;web_search&quot;, &quot;description&quot;: &quot;Search the web&quot;,": "{&quot;name&quot;: &quot;web_search&quot;, &quot;description&quot;: &quot;웹 검색&quot;,",
        "Conversation History": "대화 기록",
        "user: &quot;What's the weather in Beijing today?&quot;": "user: &quot;베이징은 오늘 날씨가 어때?&quot;",
        "assistant: [tool_call] → get_weather(&quot;Beijing&quot;)": "assistant: [tool_call] → get_weather(&quot;베이징&quot;)",
        "tool: {&quot;temp&quot;: &quot;23°C&quot;, &quot;conditions&quot;: &quot;clear&quot;}": "tool: {&quot;temp&quot;: &quot;23°C&quot;, &quot;conditions&quot;: &quot;맑음&quot;}",
        "Reasoning Trace": "생각 과정",
        "&lt;think&gt;The user asks about the weather. I already have the tool result,": "&lt;think&gt;사용자가 날씨를 물었고 도구 결과도 받았다.",
        "so I can directly summarize and respond without calling the tool again.&lt;/think&gt;": "도구를 다시 호출하지 않고 바로 요약해 답하면 된다.&lt;/think&gt;",
        "Current generation position →": "현재 생성 위치 →",
        "assistant: &quot;Beijing is clear today, temperature 23°C...&quot;  ← LLM is generating": "assistant: &quot;베이징은 오늘 맑고, 기온은 23°C입니다...&quot;  ← LLM 생성 중",
        "Context": "컨텍스트",
        "Window": "윈도",
        "Window size: Qwen3 = 32K tokens | Claude = 200K | Gemini = 2M": "윈도 크기: Qwen3 = 32K토큰 | Claude = 200K | Gemini = 2M",
        "All content serialized into token stream → processed by Transformer attention mechanism": "모든 내용을 토큰 스트림으로 직렬화 → Transformer 어텐션 처리",
    },
    "fig2-2.svg": {
        "Local Hardware": "로컬 하드웨어",
        "MLX Inference Backend": "MLX 추론 백엔드",
        "0.6B parameters · Q4 quantization": "매개변수 6억 개 · Q4 양자화",
        "&gt; 100 tokens/s": "초당 100토큰 이상",
        "ReAct + Tool calling capability": "ReAct + 도구 호출 역량",
        "Tool Registry": "도구 레지스트리",
        "ReAct Loop": "ReAct 루프",
        "user: &quot;What's the time and weather in Vancouver?&quot;": "user: &quot;밴쿠버의 현재 시각과 날씨는?&quot;",
        "Need to call get_current_time": "get_current_time과",
        "and get_temperature tools": "get_temperature 도구를 호출해야 함",
        "Continue loop": "루프 계속",
        "Final output:": "최종 출력:",
        "&quot;Vancouver: 05:18 AM, 13.2°C,": "&quot;밴쿠버: 오전 05:18, 13.2°C,",
        "  clear sky, humidity 93%&quot;": "  맑음, 습도 93%&quot;",
        "Streaming key timings": "스트리밍 핵심 시점",
        "&lt;think&gt;... → hidden, not shown to user": "&lt;think&gt;... → 숨김, 사용자에게 표시하지 않음",
        "plain text → real-time streaming display": "일반 텍스트 → 실시간 스트리밍 표시",
        "&lt;tool_call&gt; → parse and execute tool": "&lt;tool_call&gt; → 파싱 후 도구 실행",
    },
    "fig2-3.svg": {
        "# Tools": "# 도구",
        "You may call one or more functions...": "하나 이상의 함수를 호출할 수 있습니다...",
        "&quot;What's the weather like in Beijing today?&quot;": "&quot;베이징은 오늘 날씨가 어때?&quot;",
        "&lt;think&gt;Need to query weather, call get_weather tool&lt;/think&gt;": "&lt;think&gt;날씨 조회를 위해 get_weather 도구 호출&lt;/think&gt;",
        "&lt;tool_call&gt;{&quot;name&quot;:&quot;get_weather&quot;,&quot;args&quot;:{&quot;city&quot;:&quot;Beijing&quot;}}&lt;/tool_call&gt;": "&lt;tool_call&gt;{&quot;name&quot;:&quot;get_weather&quot;,&quot;args&quot;:{&quot;city&quot;:&quot;베이징&quot;}}&lt;/tool_call&gt;",
        "&lt;tool_response&gt;{&quot;temp&quot;:&quot;23°C&quot;,&quot;sky&quot;:&quot;clear&quot;}&lt;/tool_response&gt;": "&lt;tool_response&gt;{&quot;temp&quot;:&quot;23°C&quot;,&quot;sky&quot;:&quot;맑음&quot;}&lt;/tool_response&gt;",
        "← LLM starts generating new tokens from here": "← LLM이 여기서부터 새 토큰 생성",
        "special": "특수",
        "tokens": "토큰",
    },
    "fig2-4.svg": {
        "Request 1": "요청 1",
        "System Prompt + Tools (1200 tokens)": "시스템 프롬프트 + 도구(1,200토큰)",
        "user: &quot;How's the weather?&quot;": "user: &quot;날씨가 어때?&quot;",
        "→ generate response": "→ 답변 생성",
        "Request 2": "요청 2",
        "System Prompt + Tools (cache hit ✓)": "시스템 프롬프트 + 도구(캐시 적중 ✓)",
        "user: &quot;What time is it?&quot;": "user: &quot;지금 몇 시야?&quot;",
        "KV reuse": "KV 재사용",
        "Request 3": "요청 3",
        "(system prompt changed)": "(시스템 프롬프트 변경)",
        "System + Tools + &quot;Time: 10:30:45&quot;": "시스템 + 도구 + &quot;시각: 10:30:45&quot;",
        "→ full recomputation ✗": "→ 전체 재계산 ✗",
        "Performance Comparison (3000 token context)": "성능 비교(3,000토큰 컨텍스트)",
        "cache hit": "캐시 적중",
        "cache miss": "캐시 미적중",
        "~0.5 seconds": "약 0.5초",
        "3 - 5 seconds": "3~5초",
        "Cost": "비용",
        "only new tokens billed": "새 토큰만 과금",
        "all tokens rebilled": "전체 토큰 재과금",
    },
    "fig2-5.svg": {
        "No system prompt": "시스템 프롬프트 없음",
        "With system prompt": "시스템 프롬프트 있음",
        "System Prompt + Tools": "시스템 프롬프트 + 도구",
        "&quot;Help me contact Xfinity to negotiate&quot;": "&quot;Xfinity에 연락해 요금을 협상해 줘&quot;",
        "phone_call(Xfinity) → 1st attempt": "phone_call(Xfinity) → 1차 시도",
        "Result: waited 45 minutes, not connected": "결과: 45분 대기, 연결 실패",
        "web_search(&quot;Xfinity deals&quot;)": "web_search(&quot;Xfinity 할인&quot;)",
        "Result: [large amount of search content...]": "결과: [많은 검색 내용...]",
        "phone_call(Xfinity) → 2nd attempt": "phone_call(Xfinity) → 2차 시도",
        "Result: connected, quoted $65/month": "결과: 연결됨, 월 $65 제시",
        "phone_call(Xfinity) → 3rd attempt": "phone_call(Xfinity) → 3차 시도",
        "Result: confirmed price reduction to $59/month": "결과: 월 $59로 할인 확인",
        "&quot;Can you call again to follow up?&quot;": "&quot;한 번 더 전화해 확인해 줘&quot;",
        "→ Model needs to scan entire context to &quot;count&quot;": "→ 모델이 전체 컨텍스트를 훑어 호출 횟수를 세야 함",
        "number of calls made, prone to miscounting": "호출 횟수를 잘못 셀 가능성이 큼",
        "[ Same trajectory content ]": "[같은 궤적 내용]",
        "phone_call called 3 times (Xfinity: 3)": "phone_call 3회 호출(Xfinity: 3)",
        "Constraint check: limit reached (3/3) ✗": "제약 확인: 한도 도달(3/3) ✗",
        "TODO: [✓]Contact Xfinity [✓]Confirm price reduction": "TODO: [✓]Xfinity 연락 [✓]요금 할인 확인",
        "Current time: 2025-09-14 10:30": "현재 시각: 2025-09-14 10:30",
        "Current status: waiting for user confirmation": "현재 상태: 사용자 확인 대기",
        "→ Model directly reads refined status": "→ 모델이 정제된 상태를 바로 읽음",
        "Accurately follows constraints, no more calls": "제약을 정확히 지켜 더 전화하지 않음",
        "VS": "비교",
    },
    "fig2-6.svg": {
        "Strategy": "전략",
        "Tokens": "토큰",
        "Ratio": "비율",
        "Iters": "반복",
        "Result": "결과",
        "Token usage": "토큰 사용량",
        "No compression": "압축 없음",
        "5 (Failed)": "5(실패)",
        "✗ Failure": "✗ 실패",
        "Individual summary": "개별 요약",
        "✓ Success": "✓ 성공",
        "Combined summary": "통합 요약",
        "Context-aware": "컨텍스트 인식",
        "Aware + citation": "컨텍스트 인식 + 인용",
        "Adaptive window": "적응형 윈도",
        "Context-aware compression: 77% token reduction, highest success rate, fewest iterations": "컨텍스트 인식 압축: 토큰 77% 절감 · 가장 높은 성공률 · 가장 적은 반복 횟수",
        "Key: incorporate query intent and existing information into compression decisions": "핵심: 질의 의도와 기존 정보를 압축 판단에 함께 반영",
    },
    "fig2-8.svg": {
        "Layer 1: Metadata (loaded at startup, ~200 tokens)": "1계층: 메타데이터(시작할 때 로드, 약 200토큰)",
        "skills: [{name: &quot;PPTX&quot;, desc: &quot;Create PowerPoint presentations from content&quot;}": "skills: [{name: &quot;PPTX&quot;, desc: &quot;내용으로 PowerPoint 제작&quot;}",
        "        {name: &quot;PDF&quot;,  desc: &quot;Extract and analyze PDF documents&quot;}, ...]": "        {name: &quot;PDF&quot;,  desc: &quot;PDF 문서 추출 및 분석&quot;}, ...]",
        "Task trigger: &quot;Generate PPT from paper&quot;": "작업 트리거: &quot;논문으로 PPT 만들어 줘&quot;",
        "Layer 2: SKILL.md Core Flow (loaded on demand, ~2K tokens)": "2계층: SKILL.md 핵심 흐름(필요할 때 로드, 약 2K토큰)",
        "PPTX Skill Core Flow:": "PPTX Skill 핵심 흐름:",
        "1. markitdown extracts text → 2. Unzip PPTX to access XML": "1. markitdown으로 텍스트 추출 → 2. PPTX 압축을 풀어 XML 접근",
        "3. Modify slide{N}.xml content → 4. Repackage as .pptx": "3. slide{N}.xml 내용 수정 → 4. .pptx로 다시 압축",
        "References: → html2pptx.md | → reference.md | → scripts/": "참고 자료: → html2pptx.md | → reference.md | → scripts/",
        "Need detailed method: &quot;Create PPT using HTML template&quot;": "세부 방법 필요: &quot;HTML 템플릿으로 PPT 만들기&quot;",
        "Layer 3: Sub-documents (selective deep dive, loaded on demand)": "3계층: 하위 문서(필요한 자료만 선택적으로 로드)",
        "HTML template → PPT": "HTML 템플릿 → PPT",
        " complete workflow": " 전체 워크플로",
        "XML format specification": "XML 형식 명세와",
        " and technical details": " 기술 세부 사항",
        "Executable tools:": "실행 가능한 도구:",
        "thumbnail.py etc.": "thumbnail.py 등",
        "Fixed metadata → KV Cache friendly | Dynamic content appended → Cache not broken": "고정 메타데이터 → KV Cache에 유리 | 동적 내용은 끝에 추가 → 캐시 유지",
    },
    "fig2-9.svg": {
        "Original dialogue:": "원래 대화:",
        "&quot;I am a senior engineer at TechCorp, leading a team of 5 to build a recommendation system, using ML for three years&quot;": "&quot;저는 TechCorp의 선임 엔지니어로, 5명 팀을 이끌며 추천 시스템을 만들고 있고 ML 경력은 3년입니다&quot;",
        "Simple Notes": "단순 메모",
        "Atomic facts": "개별 사실",
        "&quot;User company: TechCorp&quot;": "&quot;사용자 회사: TechCorp&quot;",
        "&quot;User Position: Senior Engineer&quot;": "&quot;사용자 직급: 선임 엔지니어&quot;",
        "&quot;User Team: 5 people&quot;": "&quot;사용자 팀: 5명&quot;",
        "&quot;User Expertise: Recommendation System&quot;": "&quot;사용자 전문 분야: 추천 시스템&quot;",
        "Pros: O(1) operation,": "장점: O(1) 연산,",
        "extremely low overhead": "오버헤드가 매우 낮음",
        "Cons: Complete loss of": "단점: 연관성이",
        "relevance": "완전히 사라짐",
        "Enhanced Notes": "확장 메모",
        "Full Paragraph": "전체 문단",
        "&quot;Senior engineer at": "&quot;TechCorp의 선임 엔지니어,",
        "TechCorp, leads a team": "추천 시스템을 만드는",
        "of 5 building a rec.": "5명 팀을 이끌고 있으며",
        "system, 3 yrs in ML.&quot;": "ML 경력은 3년.&quot;",
        "Pros: Semantic": "장점: 의미적",
        "completeness": "완결성",
        "Cons: Redundancy +": "단점: 중복 +",
        "complex updates": "복잡한 갱신",
        "JSON Cards": "JSON 카드",
        "Hierarchical Structure": "계층 구조",
        "  company: &quot;TechCorp&quot;": "  company: &quot;TechCorp&quot;",
        "  title: &quot;Senior Engineer&quot;": "  title: &quot;선임 엔지니어&quot;",
        "Pros: Partial updates": "장점: 부분 갱신",
        "Cons: Rigid classification": "단점: 경직된 분류",
        "Adv. JSON Cards": "고급 JSON 카드",
        "Contextualized Knowledge": "맥락화된 지식",
        ' title: &quot;Senior Engineer&quot;,': ' title: &quot;선임 엔지니어&quot;,',
        ' backstory: &quot;Self-introduction&quot;,': ' backstory: &quot;자기소개&quot;,',
        "Pros: Disambiguation +": "장점: 모호성 해소 +",
        "traceability": "추적 가능성",
        "Cons: High generation cost": "단점: 높은 생성 비용",
        "Three-Level Evaluation Framework": "3단계 평가 체계",
        "Level 1: Basic Recall": "1단계: 기본 회상",
        "Store and retrieve direct information": "직접 정보를 저장하고 검색",
        "&quot;My membership number is 12345&quot; → Exact return": "&quot;내 회원 번호는 12345&quot; → 정확히 반환",
        "Level 2: Multi-session Retrieval": "2단계: 세션 간 검색",
        "Cross-session associative reasoning": "세션을 넘나드는 연관 추론",
        "&quot;Schedule maintenance for my car&quot; → Identify two cars": "&quot;내 차 정비를 예약해 줘&quot; → 차량 두 대 식별",
        "Level 3: Proactive Service": "3단계: 선제적 서비스",
        "Integrate multiple memories, anticipatory assistance": "여러 기억을 통합해 미리 지원",
        "Book international flight → Discover passport is about to expire": "국제선 예약 → 여권 만료가 임박했음을 발견",
    },
    "fig2-10.svg": {
        "Request 1": "요청 1",
        "System Prompt + Tools (1200 tokens)": "시스템 프롬프트 + 도구(1,200토큰)",
        "user: &quot;What's the weather like?&quot;": "user: &quot;오늘 날씨 어때?&quot;",
        "→ Generate response": "→ 답변 생성",
        "Request 2": "요청 2",
        "System Prompt + Tools (cache hit ✓)": "시스템 프롬프트 + 도구(캐시 적중 ✓)",
        "user: &quot;What time is it?&quot;": "user: &quot;지금 몇 시야?&quot;",
        "KV reuse": "KV 재사용",
        "Request 3": "요청 3",
        "(system prompt changed)": "(시스템 프롬프트 변경)",
        "System + Tools + &quot;Time: 10:30:45&quot;": "시스템 + 도구 + &quot;시각: 10:30:45&quot;",
        "→ Full recomputation ✗": "→ 전체 재계산 ✗",
        "Performance comparison (3000 token total context)": "성능 비교(전체 컨텍스트 3,000토큰)",
        "Cache hit": "캐시 적중",
        "Cache miss": "캐시 미적중",
        "~0.5 seconds": "약 0.5초",
        "3-5 seconds": "3~5초",
        "Cost": "비용",
        "New tokens only": "새 토큰만 과금",
        "All tokens rebilled": "전체 토큰 재과금",
    },
    "fig2-11.svg": {
        "Layer 1: Metadata (loaded at startup, ~300 tokens)": "1계층: 메타데이터(시작할 때 로드, 약 300토큰)",
        "skills: [{name: &quot;PPTX&quot;, desc: &quot;Create PowerPoint presentations from content&quot;}": "skills: [{name: &quot;PPTX&quot;, desc: &quot;내용으로 PowerPoint 제작&quot;}",
        "        {name: &quot;PDF&quot;,  desc: &quot;Extract and analyze PDF documents&quot;}, ...]": "        {name: &quot;PDF&quot;,  desc: &quot;PDF 문서 추출 및 분석&quot;}, ...]",
        "Task trigger: \"Generate PPT from paper\"": "작업 트리거: \"논문으로 PPT 만들어 줘\"",
        "Layer 2: SKILL.md core flow (loaded on demand, ~2K tokens)": "2계층: SKILL.md 핵심 흐름(필요할 때 로드, 약 2K토큰)",
        "PPTX Skill core flow:": "PPTX Skill 핵심 흐름:",
        "1. markitdown extract text → 2. Unzip PPTX to access XML": "1. markitdown으로 텍스트 추출 → 2. PPTX 압축을 풀어 XML 접근",
        "3. Modify slide{N}.xml content → 4. Repackage as .pptx": "3. slide{N}.xml 내용 수정 → 4. .pptx로 다시 압축",
        "References: → html2pptx.md | → reference.md | → scripts/": "참고 자료: → html2pptx.md | → reference.md | → scripts/",
        "Need detailed method: \"Create PPT with HTML template\"": "세부 방법 필요: \"HTML 템플릿으로 PPT 만들기\"",
        "Layer 3: Sub-documents (selective deep dive, loaded on demand)": "3계층: 하위 문서(필요한 자료만 선택적으로 로드)",
        "Complete workflow of": "전체 워크플로:",
        "HTML template → PPT": "HTML 템플릿 → PPT",
        "XML format specification": "XML 형식 명세와",
        "and technical details": "기술 세부 사항",
        "Executable tools:": "실행 가능한 도구:",
        "thumbnail.py etc.": "thumbnail.py 등",
        "Fixed metadata → KV Cache friendly | Dynamic content appended → Cache not invalidated": "고정 메타데이터 → KV Cache에 유리 | 동적 내용은 끝에 추가 → 캐시 유지",
    },
    "fig2-12.svg": {
        "{ role: \"system\", content: \"You are Claude Code assistant...\" }": "{ role: \"system\", content: \"당신은 Claude Code 비서입니다...\" }",
        "fixed": "고정",
        "{ role: \"user\", content: \"Help me generate a PPT from this PDF\" }": "{ role: \"user\", content: \"이 PDF로 PPT를 만들어 줘\" }",
        "     Available skills: pdf, pptx, ...&lt;/system-reminder&gt;\" }": "     사용 가능한 스킬: pdf, pptx, ...&lt;/system-reminder&gt;\" }",
        "ⓐ Skill listing": "ⓐ 스킬 목록",
        "Harness emit-once": "Harness가 한 번만 삽입",
        "~300 tokens": "약 300토큰",
        "{ role: \"tool\", content: \"Launching skill: pptx\" }   ← placeholder": "{ role: \"tool\", content: \"스킬 실행: pptx\" }   ← 자리표시자",
        "  content: \"Base directory: ...\\n# PPTX Skill": "  content: \"기준 디렉터리: ...\\n# PPTX Skill",
        "     ## Workflow: 1. Use markitdown...\" }": "     ## 워크플로: 1. markitdown 사용...\" }",
        "ⓑ Skill content": "ⓑ 스킬 내용",
        "Skill tool emit-once": "Skill 도구가 한 번만 삽입",
        "~2k tokens": "약 2K토큰",
        "{ role: \"tool\", content: \"...PDF text content...\" }": "{ role: \"tool\", content: \"...PDF 본문...\" }",
        "{ role: \"tool\", content: \"Wrote 12345 bytes\" }": "{ role: \"tool\", content: \"12,345바이트 작성 완료\" }",
        "Subsequent tool_use /": "이후 tool_use /",
        "tool_result continues": "tool_result가 끝에",
        "append to end": "계속 추가됨",
        "... subsequent rounds ...": "... 이후 라운드 ...",
        "ⓐ and ⓑ are both emit-once: after paying cache_creation once, they permanently reside in the cache prefix and will not move with subsequent tool_use": "ⓐ와 ⓑ는 한 번만 삽입된다. cache_creation 비용을 한 번 내면 캐시 접두부에 고정되고 이후 tool_use에도 위치가 바뀌지 않는다",
    },
    "fig2-13.svg": {
        "Turn 1 completed": "1턴 완료",
        "Turn 2 completed": "2턴 완료",
        "Turn 3 completed": "3턴 완료",
        "(first load PPTX skill)": "(PPTX 스킬 첫 로드)",
        "(read PDF file)": "(PDF 파일 읽기)",
        "(write HTML)": "(HTML 작성)",
        "NEW": "신규",
        "HIT": "적중",
        "★ skill_listing": "★ 스킬 목록",
        "★ skill_content": "★ 스킬 내용",
        "cache_creation for this turn": "이번 턴의 cache_creation",
        "≈ 2.5k tokens": "약 2.5K토큰",
        "≈ 0.5k tokens": "약 0.5K토큰",
        "≈ 0.4k tokens": "약 0.4K토큰",
        "NEW = new tokens added this turn, pay cache_creation once": "신규 = 이번 턴에 추가된 토큰, cache_creation 비용은 한 번만 지불",
        "HIT = already in cache prefix, free hit this turn": "적중 = 이미 캐시 접두부에 있어 이번 턴에는 무료로 재사용",
        "— content not yet generated this turn": "— 이번 턴에서 아직 생성되지 않은 내용",
        "★ Mark attachment with emit-once: pay cache_creation only on Turn 1,": "★ 한 번만 삽입하도록 표시: 1턴에서만 cache_creation 비용을 지불하고",
        "      then permanent HIT for all subsequent turns, marginal cost zero.": "      이후 모든 턴에서 계속 적중하므로 추가 비용은 0이다.",
        "Note: once inserted, the index position of each message never moves; new content is only appended to the end of the array.": "참고: 한 번 삽입된 메시지의 인덱스는 바뀌지 않으며 새 내용은 배열 끝에만 추가된다.",
    },
    "fig2-14.svg": {
        "No status bar": "상태 표시줄 없음",
        "With status bar": "상태 표시줄 있음",
        "System Prompt + Tools": "시스템 프롬프트 + 도구",
        "\"Help me contact Xfinity to negotiate\"": "\"Xfinity에 연락해 요금을 협상해 줘\"",
        "phone_call(Xfinity) → 1st attempt": "phone_call(Xfinity) → 1차 시도",
        "Result: waited 45 minutes, not connected": "결과: 45분 대기, 연결 실패",
        "web_search(&quot;Xfinity deals&quot;)": "web_search(&quot;Xfinity 할인&quot;)",
        "Result: [large amount of search content...]": "결과: [많은 검색 내용...]",
        "phone_call(Xfinity) → 2nd attempt": "phone_call(Xfinity) → 2차 시도",
        "Result: connected, quoted $65/month": "결과: 연결됨, 월 $65 제시",
        "phone_call(Xfinity) → 3rd attempt": "phone_call(Xfinity) → 3차 시도",
        "Result: confirmed price reduction to $59/month": "결과: 월 $59로 할인 확인",
        "\"Can you call again to follow up?\"": "\"한 번 더 전화해 확인해 줘\"",
        "→ Model needs to scan entire context to \"count\"": "→ 모델이 전체 컨텍스트를 훑어 호출 횟수를 세야 함",
        "how many calls were made, easy to miscount": "잘못 셀 가능성이 큼",
        "[ Same trajectory content ]": "[같은 궤적 내용]",
        "phone_call called 3 times (Xfinity: 3)": "phone_call 3회 호출(Xfinity: 3)",
        "Constraint check: reached limit (3/3) ✗": "제약 확인: 한도 도달(3/3) ✗",
        "TODO: [✓]Contact Xfinity [✓]Confirm price reduction": "TODO: [✓]Xfinity 연락 [✓]요금 할인 확인",
        "Current time: 2025-09-14 10:30": "현재 시각: 2025-09-14 10:30",
        "Current status: waiting for user confirmation": "현재 상태: 사용자 확인 대기",
        "→ Model directly reads the refined state": "→ 모델이 정제된 상태를 바로 읽음",
        "Accurately follows constraints, no more calls": "제약을 정확히 지켜 더 전화하지 않음",
        "VS": "비교",
    },
    "fig2-15.svg": {
        "{ role: \"system\", content: \"You are a telecom customer service agent...\" }": "{ role: \"system\", content: \"당신은 통신사 고객 서비스 Agent입니다...\" }",
        "fixed": "고정",
        "{ role: \"user\", content: \"Help me cancel my plan\" }": "{ role: \"user\", content: \"요금제를 해지해 줘\" }",
        "{ role: \"tool\", content: \"This plan has a contract period...\" }": "{ role: \"tool\", content: \"이 요금제에는 약정 기간이 있습니다...\" }",
        "{ role: \"assistant\", content: \"Your plan is within the contract period...\" }": "{ role: \"assistant\", content: \"현재 약정 기간 중입니다...\" }",
        "... more conversation turns ...": "... 더 많은 대화 턴 ...",
        "{ role: \"user\", content: \"Then help me check my call records\" }": "{ role: \"user\", content: \"그럼 통화 내역을 확인해 줘\" }",
        "user follow-up": "사용자 후속 요청",
        "  Called 3/3 times · TODO: Cancel plan (in progress)&lt;/agent_status&gt;\" }": "  전화 3/3회 · TODO: 요금제 해지(진행 중)&lt;/agent_status&gt;\" }",
        "Agent framework insertion": "Agent가 삽입한",
        "agent status bar": "상태 표시줄",
        "model starts generating from here": "모델이 여기서부터 생성",
        "← adjacent to model generation start, receives highest attention weight": "← 생성 시작점과 가까워 가장 높은 어텐션 가중치를 받음",
    },
    "fig2-16.svg": {
        "Strategy": "전략",
        "Tokens": "토큰",
        "Ratio": "비율",
        "Iters": "반복",
        "Result": "결과",
        "Token usage": "토큰 사용량",
        "No Compression": "압축 없음",
        "5 (Failed)": "5(실패)",
        "✗ Failed": "✗ 실패",
        "Individual Summary": "개별 요약",
        "✓ Success": "✓ 성공",
        "Combined Summary": "통합 요약",
        "Context-Aware": "컨텍스트 인식",
        "Awareness + Citation": "컨텍스트 인식 + 인용",
        "Adaptive Window": "적응형 윈도",
        "Context-Aware Compression: 77% token reduction, highest success rate, fewest iterations": "컨텍스트 인식 압축: 토큰 77% 절감 · 가장 높은 성공률 · 가장 적은 반복 횟수",
        "Key: Incorporate query intent and existing information into compression decisions": "핵심: 질의 의도와 기존 정보를 압축 판단에 함께 반영",
    },
    "fig2-17.svg": {
        "Each search returns ~70K characters → strategies handle it differently": "검색 1회당 약 7만 자 반환 → 전략마다 처리 방식이 다르다",
        "① No compression": "① 압축 없음",
        "Directly keep": "그대로 유지",
        "Full original text into context": "원문 전체를 컨텍스트에 삽입",
        "&gt; 110K tok → overflow": "&gt; 110K토큰 → 초과",
        "② Individual summary": "② 개별 요약",
        "Independent summary": "독립적으로 요약",
        "Each result independently generates 2-3 paragraph summaries": "각 결과를 따로 2~3개 문단으로 요약",
        "123K tok · 6.8%": "123K토큰 · 6.8%",
        "③ Combined summary": "③ 통합 요약",
        "Merged summary": "한꺼번에 요약",
        "All results concatenated then unified summary": "모든 결과를 합친 뒤 한 번에 요약",
        "55K tok · 2.1%": "55K토큰 · 2.1%",
        "④ Context-aware": "④ 컨텍스트 인식",
        "Intelligent compression": "질의 맞춤 압축",
        "Given query + context → targeted compression": "질의 + 컨텍스트를 반영해 필요한 내용만 압축",
        "25K tok · 0.9%": "25K토큰 · 0.9%",
        "⑤ Context-aware + citation": "⑤ 인식 + 인용",
        "Intelligent + traceability": "압축 + 추적",
        "Compressed content + retain URL citation markers": "내용은 압축하고 URL 인용 표시는 유지",
        "45K tok · 1.4%": "45K토큰 · 1.4%",
        "⑥ Adaptive window": "⑥ 적응형 윈도",
        "Deferred compression": "압축 시점 지연",
        "&lt; 80% window keep original text, batch compress when exceeded": "윈도 80% 미만이면 원문 유지, 넘으면 일괄 압축",
        "181K tok · maximum fidelity": "181K토큰 · 원문 충실도 최대",
    },
    "fig3-1.svg": {
        "用户记忆（个体尺度）": "사용자 메모리(개인 단위)",
        "知识库（群体尺度）": "지식 베이스(집단 단위)",
        "· 记忆层次 · 三层次评估": "· 메모리 계층 · 3단계 평가",
        "· 四种存储格式": "· 네 가지 저장 형식",
        "· 认知类型：情景 · 语义 · 程序": "· 인지 유형: 일화 · 의미 · 절차",
        "· 记忆框架：Mem0 · Memobase": "· 메모리 프레임워크: Mem0 · Memobase",
        "· 压缩整理 · 隐私分级": "· 압축·정리 · 개인정보 등급화",
        "· 文档分块 · 多模态提取": "· 문서 청킹 · 멀티모달 추출",
        "· 稠密/稀疏嵌入 · 混合检索": "· 밀집/희소 임베딩 · 하이브리드 검색",
        "· 结构化索引：RAPTOR · GraphRAG": "· 구조화 인덱스: RAPTOR · GraphRAG",
        "· 文件系统范式 · 智能体化 RAG": "· 파일 시스템 패러다임 · Agentic RAG",
        "· 上下文感知检索 · 深度知识提取": "· 컨텍스트 인식 검색 · 심층 지식 추출",
        "共享底层：检索技术": "공통 기반: 검색 기술",
        "文档分块 · 向量/关键词嵌入 · 混合检索 · 重排序": "문서 청킹 · 벡터/키워드 임베딩 · 하이브리드 검색 · 재순위화",
        "两条线索最终汇合于「双层记忆架构」：Advanced JSON Cards 常驻概览 + 上下文感知检索按需取细节": "2계층 메모리 아키텍처: 고급 JSON 카드로 개요 유지 + 컨텍스트 인식 검색으로 필요할 때 세부 정보 조회",
    },
    "fig3-2.svg": {
        "Simple Notes": "단순 노트",
        "&quot;用户邮箱：": "&quot;사용자 이메일:",
        "✓ 原子事实 · O(1)": "✓ 원자적 사실 · O(1)",
        "✓ 开销极低": "✓ 오버헤드 매우 낮음",
        "✗ 关联性丢失": "✗ 연관성 손실",
        "Enhanced Notes": "확장 노트",
        "&quot;在 TechCorp 任": "&quot;TechCorp의",
        "高级工程师，带": "수석 엔지니어,",
        "5 人推荐团队…&quot;": "추천 팀 5명 이끔…&quot;",
        "✓ 整段叙事": "✓ 문단 전체 서술",
        "✓ 语义完整": "✓ 의미 완전",
        "✗ 冗余 · 难更新": "✗ 중복 · 갱신 어려움",
        "✗ 长文难检索": "✗ 긴 글은 검색 어려움",
        "JSON Cards": "JSON 카드",
        "（类别→键值）": "(범주→키-값)",
        "✓ 三层结构化": "✓ 3단계 구조",
        "✓ 支持部分更新": "✓ 부분 갱신 지원",
        "✗ 刚性分类": "✗ 경직된 분류",
        "Advanced JSON Cards": "고급 JSON 카드",
        "✓ 消歧 · 知识管理": "✓ 모호성 해소 · 지식 관리",
        "✓ 带来源与关系": "✓ 출처와 관계 포함",
        "✗ 生成维护成本高": "✗ 생성·유지 비용 높음",
        "简单性": "단순성",
        "表达力": "표현력",
        "简单性递减，表达力递增": "단순성은 낮아지고 표현력은 높아짐",
    },
    "fig3-3.svg": {
        "提取阶段": "추출 단계",
        "新对话结束": "새 대화 종료",
        "触发记忆更新": "메모리 갱신 시작",
        "LLM 提取": "LLM 추출",
        "近期对话 + 已有摘要": "최근 대화 + 기존 요약",
        "候选记忆": "후보 메모리",
        "&quot;用户搬到了上海&quot;": "&quot;사용자가 상하이로 이사했다&quot;",
        "更新阶段": "갱신 단계",
        "向量检索": "벡터 검색",
        "相近的已有记忆": "유사한 기존 메모리",
        "LLM 对比决策": "LLM 비교·결정",
        "检索到&quot;住在北京&quot;": "&quot;베이징 거주&quot; 메모리 검색",
        "入库全新信息": "새 정보 저장",
        "修正已有记忆": "기존 메모리 수정",
        "删除被否定的": "부정된 메모리 삭제",
        "重复则不操作": "중복이면 작업 없음",
        "例：北京→上海\n判为 UPDATE": "도시 변경 = UPDATE",
    },
    "fig3-4.svg": {
        "工作记忆": "작업 기억",
        "Working Memory": "Working Memory",
        "当前任务状态": "현재 작업 상태",
        "情景记忆": "일화 기억",
        "Episodic": "Episodic",
        "带元数据的事件序列": "메타데이터가 있는 사건 순서",
        "语义记忆": "의미 기억",
        "Semantic": "Semantic",
        "抽象出的一般知识": "추상화한 일반 지식",
        "程序记忆": "절차 기억",
        "Procedural": "Procedural",
        "可复用的行为流程": "재사용 가능한 행동 절차",
        "选择性转移 ↑": "선택적으로 이동 ↑",
        "↓ 激活加载": "↓ 활성화하여 불러오기",
        "长期记忆（跨会话）": "장기 기억(세션 간)",
        "工作记忆与长期记忆动态交互：重要信息选择性写入，相关记忆按需激活": "작업 기억↔장기 기억: 중요한 정보는 선택 저장, 관련 메모리는 필요할 때 활성화",
    },
    "fig3-5.svg": {
        "① 用户查询": "① 사용자 질의",
        "&quot;故意杀人罪判几年？&quot;": "&quot;고의살인죄의 형량은?&quot;",
        "② 检索 (Retrieval)": "② 검색(Retrieval)",
        "稠密检索 + BM25": "밀집 검색 + BM25",
        "→ Top-K 文本块": "→ 상위 K개 텍스트 조각",
        "③ 增强 (Augment)": "③ 증강(Augment)",
        "查询 + 检索结果": "질의 + 검색 결과",
        "→ 构造完整 Prompt": "→ 전체 프롬프트 구성",
        "④ 生成 (Generate)": "④ 생성(Generate)",
        "LLM 综合上下文": "LLM이 컨텍스트 종합",
        "→ 生成回答": "→ 답변 생성",
        "具体数据流示例": "구체적인 데이터 흐름 예시",
        "检索到的文本块": "검색된 텍스트 조각",
        "《刑法》第232条：故意杀人的，处死刑、": "《형법》 제232조: 고의로 사람을 살해한 자는 사형,",
        "无期徒刑或十年以上有期徒刑...": "무기징역 또는 10년 이상의 유기징역에 처한다...",
        "增强后的 Prompt": "증강된 프롬프트",
        "基于以下法条回答问题：": "다음 법 조항을 바탕으로 질문에 답하시오:",
        "[《刑法》第232条...]  问：故意杀人罪判几年？": "[《형법》 제232조...] 질문: 고의살인죄의 형량은?",
        "生成的回答": "생성된 답변",
        "根据《刑法》第232条，故意杀人罪处死刑、无期徒刑或十年以上有期徒刑；": "《형법》 제232조에 따르면 고의살인죄는 사형, 무기징역 또는 10년 이상의 유기징역에 처하며,",
        "情节较轻的，处三年以上十年以下有期徒刑。": "정상이 비교적 가벼우면 3년 이상 10년 이하의 유기징역에 처한다.",
    },
    "fig3-6.svg": {
        "300维": "300차원",
        "静态词向量": "정적 단어 벡터",
        "共现关系": "동시 출현 관계",
        "预测训练": "예측 학습",
        "全局统计": "전역 통계",
        "矩阵分解": "행렬 분해",
        "+ 共现": "+ 동시 출현",
        "768维": "768차원",
        "上下文感知": "컨텍스트 인식",
        "MLM预训练": "MLM 사전 학습",
        "句子级嵌入": "문장 수준 임베딩",
        "孪生网络": "샴 네트워크",
        "对比学习": "대조 학습",
        "1024维": "1024차원",
        "多语言长文本": "다국어 긴 텍스트",
        "多阶段": "다단계",
        "混合训练": "혼합 학습",
        "静态词向量（一词一向量）": "정적 단어 벡터(단어마다 벡터 하나)",
        "上下文感知嵌入（一词多向量）": "컨텍스트 인식 임베딩(단어마다 벡터 여러 개)",
    },
    "fig3-7.svg": {
        "Layer 2（稀疏 · 长程连接）": "2계층(희소 · 장거리 연결)",
        "Layer 1（中等密度）": "1계층(중간 밀도)",
        "Layer 0（稠密 · 全节点）": "0계층(밀집 · 모든 노드)",
        "搜索从顶层开始": "검색은 최상위 계층에서 시작",
        "逐层向下精炼": "아래 계층으로 내려가며 정밀화",
        "支持增量更新 · 高召回率": "증분 갱신 지원 · 높은 재현율",
        "O(log N) 查询复杂度": "질의 복잡도 O(log N)",
    },
    "fig3-8.svg": {
        "词频饱和 (TF)": "단어 빈도 포화(TF)",
        "k₁ 控制饱和速度": "k₁이 포화 속도를 제어",
        "词频 ↑ 但贡献递减": "단어 빈도 ↑, 기여도는 감소",
        "例: 出现 5→10 次": "예: 5회→10회 등장",
        "得分仅增 ~20%": "점수는 약 20%만 증가",
        "逆文档频率 (IDF)": "역문서 빈도(IDF)",
        "衡量词的稀有度": "단어의 희소성을 측정",
        "&quot;的&quot; → IDF ≈ 0": "&quot;의&quot; → IDF ≈ 0",
        "&quot;量刑&quot; → IDF ≈ 5.2": "&quot;양형&quot; → IDF ≈ 5.2",
        "稀有词权重 &gt;&gt; 常见词": "희귀 단어 가중치 &gt;&gt; 흔한 단어",
        "长度归一化 (b)": "길이 정규화(b)",
        "b ∈ [0,1] 归一化强度": "b ∈ [0,1] 정규화 강도",
        "b=0: 不考虑长度": "b=0: 길이 무시",
        "b=1: 完全归一化": "b=1: 완전 정규화",
        "避免长文档偏倚": "긴 문서 편향 방지",
        "最终得分 = Σ  (TF饱和 × IDF加权 × 长度归一化)": "최종 점수 = Σ (TF 포화 × IDF 가중치 × 길이 정규화)",
    },
    "fig3-9.svg": {
        "用户查询": "사용자 질의",
        "&quot;kitty behavior&quot;": "&quot;야옹이 행동&quot;",
        "稠密检索": "밀집 검색",
        "语义匹配: kitty ≈ cat": "의미 일치: 야옹이 ≈ 고양이",
        "doc3: &quot;feline habits and cat play...&quot;": "doc3: &quot;고양잇과 습성과 고양이 놀이...&quot;",
        "doc7: &quot;cat grooming patterns...&quot;": "doc7: &quot;고양이 그루밍 패턴...&quot;",
        "doc1: &quot;pet care basics...&quot;": "doc1: &quot;반려동물 돌봄 기초...&quot;",
        "稀疏检索 (BM25)": "희소 검색(BM25)",
        "精确匹配: &quot;kitty&quot; 关键词": "정확 일치: &quot;야옹이&quot; 키워드",
        "doc5: &quot;kitty litter training...&quot;": "doc5: &quot;야옹이 배변 훈련...&quot;",
        "doc9: &quot;kitty adoption guide...&quot;": "doc9: &quot;야옹이 입양 안내...&quot;",
        "doc2: &quot;kitten health tips...&quot;": "doc2: &quot;아기 고양이 건강 정보...&quot;",
        "结果": "결과",
        "融合": "결합",
        "神经": "신경망",
        "重排序": "재순위화",
        "跨编码器精排": "교차 인코더 정렬",
        "最终排序 Top-N": "최종 상위 N개 순위",
    },
    "fig3-10.svg": {
        "全局摘要": "전체 요약",
        "← 根节点": "← 루트 노드",
        "聚类摘要 A": "클러스터 요약 A",
        "聚类摘要 B": "클러스터 요약 B",
        "聚类摘要 C": "클러스터 요약 C",
        "中间层 ↑": "중간 계층 ↑",
        "文本块 1": "텍스트 조각 1",
        "文本块 2": "텍스트 조각 2",
        "文本块 3": "텍스트 조각 3",
        "文本块 4": "텍스트 조각 4",
        "文本块 5": "텍스트 조각 5",
        "文本块 6": "텍스트 조각 6",
        "文本块 7": "텍스트 조각 7",
        "叶子层 ↑": "리프 계층 ↑",
        "原始文档": "원본 문서",
        "自下而上递归抽象：细节 → 主题 → 全局概览": "상향식 재귀 추상화: 세부 정보 → 주제 → 전체 개요",
    },
    "fig3-11.svg": {
        "用户": "사용자",
        "张医生-A": "장 의사 A",
        "科室：牙科": "진료과: 치과",
        "仁爱口腔医院": "인의치과병원",
        "地址": "주소",
        "徐汇区 XX 路": "쉬후이구 XX로",
        "张医生-B": "장 의사 B",
        "科室：心内科": "진료과: 심장내과",
        "华山医院": "화산병원",
        "心血管中心": "심혈관센터",
        "我的牙医": "내 치과 의사",
        "我的心脏科医生": "내 심장 전문의",
        "就职于": "근무",
        "· 多跳推理：“我的牙医所在医院的地址” = 用户 → 张医生-A → 仁爱口腔医院 → 地址，沿关系边逐跳遍历": "· 다중 홉: ‘내 치과 의사 병원 주소’ = 사용자 → 장 의사 A → 인의치과병원 → 주소(관계 간선 순회)",
        "· 实体消歧：两个同名“张医生”是图中不同节点，靠各自的关系边（牙科 / 心内科）区分。每条边 = 一个三元组（主语-关系-宾语）": "· 엔티티 구분: 동명이인 ‘장 의사’는 치과/심장내과 관계로 구분. 간선 = (주어-관계-목적어)",
    },
    "fig3-12.svg": {
        "非智能体化 RAG": "Non-Agentic RAG",
        "固定前置步骤，一次性检索": "고정된 사전 단계, 한 번만 검색",
        "用户查询": "사용자 질의",
        "检索（一次）": "검색(1회)",
        "直接生成答案": "바로 답변 생성",
        "智能体化 RAG（Agentic）": "Agentic RAG",
        "Agent 用 ReAct 主导，迭代检索": "Agent가 ReAct로 반복 검색을 주도",
        "思考：分析需求、定关键词": "생각: 요구 분석, 키워드 선정",
        "行动：调用检索工具": "행동: 검색 도구 호출",
        "观察：信息是否充分？": "관찰: 정보가 충분한가?",
        "不够": "부족",
        "充分 → 综合生成答案": "충분 → 종합하여 답변 생성",
    },
    "fig3-13.svg": {
        "Agent (ReAct 循环)": "Agent(ReAct 루프)",
        "① Thought (思考)": "① Thought(생각)",
        "② Action (行动)": "② Action(행동)",
        "③ Observation (观察)": "③ Observation(관찰)",
        "循环直到信息充分": "정보가 충분할 때까지 반복",
        "用户查询": "사용자 질의",
        "最终回答": "최종 답변",
        "工具层": "도구 계층",
        "知识库后端（可切换）": "지식 베이스 백엔드(교체 가능)",
        "混合检索": "하이브리드 검색",
        "上下文感知": "컨텍스트 인식",
    },
    "fig3-14.svg": {
        "传统分块（无上下文）": "전통적 청킹(컨텍스트 없음)",
        "该公司第二季度的收入增长了3%，": "이 회사의 2분기 매출은 3% 증가했으며,",
        "主要由新产品线驱动。": "주로 신제품군이 성장을 이끌었다.",
        "问题：&quot;该公司&quot;是谁？哪一年？": "질문: &quot;이 회사&quot;는 어디인가? 몇 년도인가?",
        "→ 检索时匹配大量无关公司的收入数据": "→ 검색할 때 관련 없는 여러 회사의 매출 데이터와 일치",
        "上下文感知分块": "컨텍스트 인식 청킹",
        "[ACME公司 2025年Q2财报·关键业绩指标]": "[ACME 2025년 2분기 실적 보고서 · 주요 성과 지표]",
        "→ 精确匹配 ACME + Q2 + 收入增长": "→ ACME + 2분기 + 매출 증가와 정확히 일치",
        "索引阶段：LLM 生成上下文前缀": "인덱싱 단계: LLM이 컨텍스트 접두사 생성",
        "原始文档": "원본 문서",
        "分块": "청킹",
        "LLM 生成前缀": "LLM이 접두사 생성",
        "(prompt caching)": "(프롬프트 캐싱)",
        "前缀 + 原文": "접두사 + 원문",
        "→ 索引": "→ 인덱싱",
        "效果：检索失败率 ↓49%（+BM25），↓67%（+重排序）—— Anthropic 数据": "효과: 검색 실패율 ↓49%(+BM25), ↓67%(+재순위화) — Anthropic 데이터",
    },
    "fig3-15.svg": {
        "阶段一：知识提取与结构化": "1단계: 지식 추출 및 구조화",
        "原始判例文书": "원본 판결문",
        "CAIL2018 数据集": "CAIL2018 데이터셋",
        "LLM 因子发现": "LLM 요인 발견",
        "自下而上 Schema": "상향식 스키마",
        "结构化 JSON": "구조화 JSON",
        "{自首:true, 赔偿:50万,": "{자수:true, 배상:50만,",
        " 伤害等级:重伤二级}": " 상해등급:중상 2급}",
        "模块化数据模式": "모듈형 데이터 스키마",
        "核心模式（自首/赔偿/前科）+ 罪名扩展模式": "핵심 스키마(자수/배상/전과) + 범죄별 확장 스키마",
        "（盗窃→涉案金额, 伤害→伤害等级）": "(절도→관련 금액, 상해→상해 등급)",
        "阶段二：因子分析与知识建模": "2단계: 요인 분석 및 지식 모델링",
        "特征向量化": "특징 벡터화",
        "独热编码 + 多热编码": "원-핫 인코딩 + 멀티-핫 인코딩",
        "+ 对数变换 + 标准化": "+ 로그 변환 + 표준화",
        "HDBSCAN 聚类": "HDBSCAN 클러스터링",
        "发现&quot;案件原型&quot;": "&quot;사건 원형&quot; 발견",
        "如: 轻微口角→轻伤": "예: 가벼운 말다툼→경상",
        "因子重要性模型": "요인 중요도 모델",
        "量化各因素权重": "각 요인의 가중치 정량화",
        "构建量刑决策逻辑": "양형 결정 로직 구축",
        "应用：对话式法律咨询 Agent": "적용: 대화형 법률 상담 Agent",
        "按因子重要性引导提问 → 检索相似案件原型 → 数据驱动的量刑分析": "요인 중요도에 따라 질문 유도 → 유사 사건 원형 검색 → 데이터 기반 양형 분석",
    },
    "fig4-1.svg": {
        "MCP Client": "MCP 클라이언트",
        "MCP Server": "MCP 서버",
        "initialize response": "응답",
        "tools/list response": "응답",
        "tools/call result": "결과",
        "① Handshake": "① 핸드셰이크",
        "② Discovery": "② 발견",
        "③ Invocation": "③ 호출",
    },
    "fig4-2.svg": {
        "Main Agent": "주 Agent",
        "How to prepare context for Sub-Agent?": "하위 Agent 컨텍스트를 어떻게 준비할까?",
        "Minimal passing": "최소 전달",
        "&quot;Query the status of order number 12345&quot;": "&quot;주문 번호 12345의 상태 조회&quot;",
        "Zero context → privacy and security": "컨텍스트 없음 → 개인 정보 보호",
        "Sub-Agent": "하위 Agent",
        "Manual filtering and passing": "수동 선별 전달",
        "&quot;User region: US": "&quot;사용자 지역: 미국",
        "Summary: Inquiry about refund&quot;": "요약: 환불 문의&quot;",
        "Explicit selection → controllable": "명시적 선택 → 제어 가능",
        "Automatic trimming and passing": "자동 가지치기 전달",
        "&quot;User info + last 3 rounds": "&quot;사용자 정보 + 최근 3턴",
        "+ relevant tool results&quot;": "+ 관련 도구 결과&quot;",
        "Rule-driven → balanced": "규칙 기반 → 균형",
        "LLM-generated context": "LLM 생성 컨텍스트",
        "&quot;LLM analyzes trajectory": "&quot;LLM이 궤적 분석",
        "→ structured context object&quot;": "→ 구조화된 컨텍스트 객체&quot;",
        "Most intelligent → 1 extra call": "가장 지능적 → 호출 1회 추가",
        "Selection guide": "선택 가이드",
        "Simple high-frequency calls": "단순 고빈도 호출",
        "Check weather, calculator": "날씨 조회, 계산기",
        "→ Minimal": "→ 최소 전달",
        "Medium complexity": "중간 복잡도",
        "Data query, file processing": "데이터 조회, 파일 처리",
        "→ Automatic trimming": "→ 자동 가지치기",
        "Complex tasks": "복잡한 작업",
        "Generate report, customer service": "보고서 생성, 고객 서비스",
        "→ LLM generation": "→ LLM 생성",
    },
    "fig4-3.svg": {
        "Event source": "이벤트 소스",
        "Email": "이메일",
        "Timer": "타이머",
        "User": "사용자",
        " &quot;subject&quot;:&quot;Re:meeting&quot;}": " &quot;subject&quot;:&quot;Re:회의&quot;}",
        "{&quot;text&quot;:&quot;Check tomorrow's weather for me": "{&quot;text&quot;:&quot;내일 날씨",
        "Event queue": "이벤트 큐",
        "Priority: normal": "우선순위: 일반",
        "Priority: urgent!": "우선순위: 긴급!",
        "Agent processing flow": "Agent 처리 흐름",
        "Fetch event": "이벤트 가져오기",
        "Router": "라우터",
        "LLM determines urgency": "LLM이 긴급도 판단",
        "Append to trace": "궤적에 추가",
        "Structured event format": "구조화된 이벤트 형식",
        "LLM inference": "LLM 추론",
        "Observe → Think → Act": "관찰 → 사고 → 행동",
        "Tool execution": "도구 실행",
        "Async/sync dispatch": "비동기/동기 분배",
        "Result handling": "결과 처리",
        "Notify/respond/store": "알림/응답/저장",
        "Loop": "반복",
    },
    "fig4-4.svg": {
        "Cancellation": "취소식",
        "(Urgent)": "(긴급)",
        "LLM reasoning...": "LLM 추론 중...",
        "⚡ user.interrupt: &quot;Stop!&quot;": "⚡ user.interrupt: &quot;중지!&quot;",
        "Tool executing...": "도구 실행 중...",
        "New LLM reasoning (including interrupt event + clear queue)": "새 LLM 추론(중단 이벤트 포함 + 큐 비우기)",
        "Queue-based": "큐식",
        "(Normal)": "(일반)",
        "Tool execution (search_web)": "도구 실행(search_web)",
        "LLM comprehensive processing": "LLM 종합 처리",
        "user: &quot;Only look at the last 1 month&quot;": "user: &quot;최근 한 달만 확인&quot;",
        "Enqueue waiting": "큐에서 대기",
        "Batch append: tool.result + user input": "일괄 추가: tool.result + 사용자 입력",
        "Parallel": "병렬식",
        "(Independent)": "(독립)",
        "Main task: Data analysis (long execution)": "주 작업: 데이터 분석(장시간 실행)",
        "user: &quot;How is the weather today?&quot;": "user: &quot;오늘 날씨가 어때?&quot;",
        "Parallel LLM": "병렬 LLM",
        "Weather": "날씨",
        "→ Reply to user immediately": "→ 사용자에게 즉시 응답",
        "Tag: [Parallel with main task]": "표시: [주 작업과 병렬 실행]",
    },
    "fig4-5.svg": {
        "External event source": "외부 이벤트 소스",
        "Web/App": "웹/App",
        "Email system": "이메일 시스템",
        "System alert": "시스템 경보",
        "Timer": "타이머",
        "FastAPI server": "FastAPI 서버",
        "HTTP endpoint": "HTTP 엔드포인트",
        "Event router": "이벤트 라우터",
        "LLM determines urgency": "LLM이 긴급도 판단",
        "Event queue": "이벤트 큐",
        "Priority sorting": "우선순위 정렬",
        "Agent loop": "Agent 루프",
        "Fetch → Reason → Execute": "가져오기 → 추론 → 실행",
        "Session management": "세션 관리",
        "Multi-threaded context": "다중 스레드 컨텍스트",
        "MCP tool server": "MCP 도구 서버",
        "Perception tools": "인지 도구",
        "execution tool": "실행 도구",
        "collaboration tool": "협업 도구",
        "notification tool": "알림 도구",
        "persistence layer": "영속 계층",
        "conversation history": "대화 이력",
        "event log": "이벤트 로그",
        "scheduled task": "예약 작업",
        "tool status": "도구 상태",
        "audit trail": "감사 추적",
    },
    "fig4-6.svg": {
        "training paradigm (strictly synchronous sequence)": "훈련 패러다임(엄격한 동기 시퀀스)",
        "API mandatory constraint": "API 강제 제약",
        "Observation": "관찰",
        "User: Check Beijing weather": "사용자: 베이징 날씨 조회",
        "Thinking": "사고",
        "Need to call weather tool": "날씨 도구 호출 필요",
        "Action": "행동",
        "22°C, sunny": "22°C, 맑음",
        "tool_call → next must be tool_result, otherwise API error": "tool_call → 다음은 반드시 tool_result, 아니면 API 오류",
        "contradiction": "모순",
        "deployment reality (asynchronous events interleaved)": "배포 현실(비동기 이벤트 삽입)",
        "Format conflict!": "형식 충돌!",
        "Waiting...": "대기 중...",
        "Tool execution ~5s": "도구 실행 약 5초",
        "User interrupts": "사용자 중단",
        "&quot;No need, ": "&quot;필요 없어, ",
        "check Shanghai's &quot;": "상하이를 확인해 줘&quot;",
        "When will tool_result arrive? ": "tool_result는 언제 도착할까?",
        "How to ensure format?": "형식을 어떻게 보장할까?",
        "placeholder": "자리표시자",
        "[Tool still executing, ": "[도구 실행 중, ",
        "prioritize interruption]": "중단을 우선 처리]",
        "Solution: placeholder fixes format + non-urgent events enqueued + only interrupt when truly urgent": "해법: 자리표시자로 형식 복구 + 비긴급 이벤트 큐 저장 + 실제 긴급 상황에만 중단",
        "Fundamental solution: next-generation models need to be trained via RL in asynchronous environments": "근본 해법: 차세대 모델을 비동기 환경에서 RL로 훈련",
    },
    "fig4-7.svg": {
        "Tool A": "도구 A",
        "Tool B": "도구 B",
        "Tool C": "도구 C",
        "Trajectory": "궤적",
        "LLM: Launch 3 tools": "LLM: 도구 3개 시작",
        "Script A: 3% per second → 33s to complete": "스크립트 A: 초당 3% → 33초 후 완료",
        "Script B: 2% per second → 50s...": "스크립트 B: 초당 2% → 50초...",
        "Script C: 1% per second → 100s...": "스크립트 C: 초당 1% → 100초...",
        "A completed": "A 완료",
        "Query B, C progress": "B, C 진행률 조회",
        "Cancel C": "C 취소",
        "B completed": "B 완료",
        "LLM: Integrate A+B results to generate report": "LLM: A+B 결과를 통합해 보고서 생성",
        "A result + B result + C cancellation record": "A 결과 + B 결과 + C 취소 기록",
        "Key: placeholder injection + async completion event + cancel_tool(task_id) API": "핵심: 자리표시자 주입 + 비동기 완료 이벤트 + cancel_tool(task_id) API",
    },
    "fig5-1.svg": {
        "Multi-platform message gateway (user interaction layer)": "다중 플랫폼 메시지 Gateway(사용자 상호작용 계층)",
        "Natural language request": "자연어 요청",
        "Coding Agent runtime (inference + execution core)": "Coding Agent 런타임(추론 + 실행 코어)",
        "Code Interpreter": "코드 인터프리터",
        "Code execution": "코드 실행",
        "Bash Shell": "Bash Shell",
        "System commands": "시스템 명령",
        "Read File": "파일 읽기",
        "Read file": "파일 읽기",
        "Write File": "파일 쓰기",
        "Write file": "파일 쓰기",
        "Edit File": "파일 편집",
        "Edit file": "파일 편집",
        "File search": "파일 검색",
        "Content search": "내용 검색",
        "Web search module": "웹 검색 모듈",
        "Web request · parsing": "웹 요청 · 파싱",
        "Browser automation": "브라우저 자동화",
        "Read / Write file": "파일 읽기 / 쓰기",
        "File system (memory · knowledge · capability hub)": "파일 시스템(메모리 · 지식 · 역량의 중추)",
        "High-level facts / user preferences": "상위 수준 사실 / 사용자 선호",
        "Daily archive / interaction logs": "일별 보관 / 상호작용 로그",
        "Agent identity and behavior rules": "Agent 정체성과 행동 규칙",
        "Knowledge base files": "지식 베이스 파일",
        "Task experience / self-evolution": "작업 경험 / 자기 진화",
        "Git version control": "Git 버전 관리",
        "Memory rollback / history audit": "메모리 롤백 / 이력 감사",
        "LLM = new operating system: shield intelligence complexity, provide unified abstraction": "LLM = 새로운 운영체제: 지능의 복잡성을 감추고 통일된 추상화 제공",
    },
    "fig5-2.svg": {
        "① Project documentation": "① 프로젝트 문서화",
        "→ Generate CLAUDE.md": "→ CLAUDE.md 생성",
        "project guide": "프로젝트 가이드",
        "② Requirement understanding": "② 요구 사항 이해",
        "&quot;Is the optimization": "&quot;최적화 목표는",
        "goal latency or": "지연인가,",
        "throughput?&quot;": "처리량인가?&quot;",
        "src/config.py (current": "src/config.py(현재",
        "parameters)": "매개변수)",
        "③ Design Document": "③ 설계 문서",
        "design.md (Scheme": "design.md(해법",
        "Comparison)": "비교)",
        "Submit design → Wait": "설계 제출 → 승인",
        "for approval": "대기",
        "After human review →": "사람의 검토 후 →",
        "Continue": "계속",
        "④ Coding and Testing": "④ Coding과 테스트",
        "old_str→new_str modify": "old_str→new_str 코드",
        "code": "수정",
        "Fix failed tests →": "실패한 테스트 수정 →",
        "Rerun": "재실행",
        "⑤ Review and Delivery": "⑤ 검토와 전달",
        "Self-review:": "자기 검토:",
        "readability/security/performance": "가독성/보안/성능",
        "Update ARCHITECTURE.md": "ARCHITECTURE.md 갱신",
        "Closed-loop feedback mechanism": "폐쇄 루프 피드백 메커니즘",
        "Test failure → Modify code → Retest": "테스트 실패 → 코드 수정 → 재테스트",
        "④ Inner loop: average 2-3 rounds to converge": "④ 내부 루프: 평균 2~3회에 수렴",
        "Lint error → Fix immediately → Recheck": "Lint 오류 → 즉시 수정 → 재검사",
        "⑤ Inner loop: automatically triggered after editing": "⑤ 내부 루프: 편집 후 자동 실행",
        "Issues found in review → Go back to ④ to modify": "검토에서 문제 발견 → ④로 돌아가 수정",
        "⑤→④ rollback: ensure delivery quality": "⑤→④ 되돌리기: 전달 품질 보장",
        "Agent status bar: cwd, git branch": "Agent 상태 표시줄: cwd, git 브랜치",
        "Agent status bar: unstaged changes": "Agent 상태 표시줄: 스테이징 전 변경",
        "Tool output: head/tail truncation": "도구 출력: 앞뒤만 남기고 자르기",
        "Persistent terminal session": "영속 터미널 세션",
        "Plan before action · Verification throughout · Documentation and code co-evolve": "행동보다 계획 우선 · 전 과정 검증 · 문서와 코드의 공동 진화",
    },
    "fig5-3.svg": {
        "Regex content match (grep)": "정규식 내용 일치(grep)",
        "Query:": "질의:",
        "Result:": "결과:",
        "Exact text → all occurrence positions": "정확한 텍스트 → 모든 출현 위치",
        "Filename match (glob)": "파일 이름 일치(glob)",
        "Path pattern → does not read file content": "경로 패턴 → 파일 내용을 읽지 않음",
        "Semantic Code Search": "의미 코드 검색",
        "&quot;Handle User Input Validation&quot;": "&quot;사용자 입력 검증 처리&quot;",
        "Natural Language → Vector + BM25 Hybrid": "자연어 → 벡터 + BM25 하이브리드",
        "Symbol Definition/Reference": "기호 정의/참조",
        "Definition: src/services/user.py:12": "정의: src/services/user.py:12",
        "Reference: src/api/routes.py:34 (import)": "참조: src/api/routes.py:34(import)",
        "Reference: src/api/routes.py:56 (call)": "참조: src/api/routes.py:56(호출)",
        "Reference: tests/test_user.py:8 (test)": "참조: tests/test_user.py:8(테스트)",
        "AST Level → Disambiguate Same Names": "AST 수준 → 같은 이름의 모호성 해소",
    },
    "fig5-4.svg": {
        "LLM Output Diff Description:": "LLM 출력 Diff 설명:",
        "→ Small Model Locates and Applies": "→ 소형 모델이 위치를 찾아 적용",
        "Advantage: Separation of": "장점: 관심사의",
        "Concerns": "분리",
        "Disadvantage: Minor": "단점: 작은",
        "Deviation Causes": "차이로도 위치가",
        "Misalignment": "어긋남",
        "Old String → New String": "이전 문자열 → 새 문자열",
        "→ Exact String Match Replacement": "→ 정확한 문자열 일치로 교체",
        "Advantage: Predictable,": "장점: 예측 가능하고",
        "Unambiguous": "모호하지 않음",
        "Disadvantage: Large": "단점: 큰 블록 삭제 시",
        "Deletions Require Full": "전체 원문을",
        "Output": "출력해야 함",
        "Line Number Positioning": "행 번호 지정",
        "Delete lines 42-43, insert:": "42~43행을 지우고 삽입:",
        "→ Line Number Specifies Exact Range": "→ 행 번호로 정확한 범위 지정",
        "Advantage: Efficient for": "장점: 큰 작업에",
        "Large Operations": "효율적",
        "Disadvantage: Line": "단점: 긴 파일에서는",
        "Numbers Error-Prone in": "행 번호 오류가",
        "Long Files": "나기 쉬움",
        "Vim-like Commands": "Vim식 명령",
        "42G  (Jump to line 42)": "42G  (42행으로 이동)",
        "cw   (Replace word)": "cw   (단어 교체)",
        "dd   (Delete line)": "dd   (행 삭제)",
        "yy/p (Copy/Paste)": "yy/p (복사/붙여넣기)",
        "→ Rich editing semantics": "→ 풍부한 편집 의미",
        "Advantage: Efficient": "장점: 이동/재구성에",
        "move/reorganize": "효율적",
        "Disadvantage: Weak": "단점: 약한 모델은",
        "models produce more": "오류를 더 많이",
        "errors": "생성함",
        "Head-tail matching": "시작-끝 일치",
        "→ Only need boundaries to locate": "→ 경계만으로 위치를 찾음",
        "Advantage: Large deletion": "장점: 전체 출력 없이",
        "without full output": "큰 블록 삭제",
        "Disadvantage: Boundary": "단점: 경계 조합이",
        "combination must be": "고유해야",
        "unique": "함",
        "Actual adoption": "실제 채택 사례",
        "Line Number Positioning": "행 번호 지정",
        "IDE deep integration scenarios": "IDE 깊은 통합 상황",
        "Head-tail matching": "시작-끝 일치",
        "Partial custom solutions": "일부 맞춤형 해법",
        "Vim commands": "Vim 명령",
        "Experimental solutions": "실험적 해법",
    },
    "fig5-5.svg": {
        "Proposer Agent": "제안자 Agent",
        "Input: Paper/content": "입력: 논문/콘텐츠",
        "paper.pdf → Extract sections/arguments/figures": "paper.pdf → 장/주장/그림 추출",
        "Output: Slidev Markdown": "출력: Slidev Markdown",
        "# Transformer Architecture": "# Transformer 아키텍처",
        "- Self-attention mechanism": "- 자기 어텐션 메커니즘",
        "- Multi-head attention": "- 다중 헤드 어텐션",
        "Reviewer Agent": "검토자 Agent",
        "Step 1: Render screenshot": "1단계: 스크린숏 렌더링",
        "Step 2: Vision LLM review": "2단계: Vision LLM 검토",
        "Review dimensions:": "검토 차원:",
        "  ✓ Text overflow boundary": "  ✓ 텍스트 경계 넘침",
        "  ✓ Layout too crowded": "  ✓ 지나치게 빽빽한 레이아웃",
        "  ✓ Image size appropriate": "  ✓ 적절한 이미지 크기",
        "  ✗ Slide 3: Text overflows right column": "  ✗ 슬라이드 3: 텍스트가 오른쪽 열을 넘음",
        "  ✗ Slide 7: Content too dense": "  ✗ 슬라이드 7: 내용이 너무 빽빽함",
        "Slidev code": "Slidev 코드",
        "Modification suggestions": "수정 제안",
        "Iterate 2-3 rounds": "2~3회 반복",
        "Why separate Proposer and Reviewer?": "제안자와 검토자를 분리하는 이유",
        "Single Agent Problem": "단일 Agent의 문제",
        "Tens of pages of rendered screenshots → context bloat": "수십 장의 렌더링 스크린숏 → 컨텍스트 폭증",
        "Code + screenshot mix → attention dispersion": "코드 + 스크린숏 혼합 → 어텐션 분산",
        "Advantages of Separation": "분리의 장점",
        "Reviewer independent context → only screenshots + code": "검토자 독립 컨텍스트 → 스크린숏 + 코드만 확인",
        "Proposer focuses on code → only receives modification suggestions": "제안자는 코드에 집중 → 수정 제안만 수신",
        "Actual Effect": "실제 효과",
        "Significantly reduces context usage": "컨텍스트 사용량 대폭 감소",
        "Fix accuracy improves significantly": "수정 정확도 대폭 향상",
    },
    "fig5-6.svg": {
        "Phase 1: PPT Generation (Proposer-Reviewer)": "1단계: PPT 생성(제안자-검토자)",
        "PDF Input": "PDF 입력",
        "Parse doc structure": "문서 구조 파싱",
        "Extract figure refs": "그림 참조 추출",
        "Content Planning": "콘텐츠 계획",
        "10-20 page structure": "10~20장 구조",
        "Extract core arguments": "핵심 주장 추출",
        "Assign figures to pages": "페이지에 그림 배치",
        "Slidev Generation": "Slidev 생성",
        "Generate page by page": "페이지별 생성",
        "Code + image layout": "코드 + 이미지 레이아웃",
        "Rendering Check": "렌더링 검사",
        "Vision LLM review": "Vision LLM 검토",
        "Overflow detection": "넘침 탐지",
        "Iterative Fix": "반복 수정",
        "Modify Slidev code": "Slidev 코드 수정",
        "Re-render and verify": "재렌더링·검증",
        "PPT completed": "PPT 완성",
        "Phase 2: Video synthesis": "2단계: 동영상 합성",
        "Screenshot per page": "페이지별 스크린숏",
        "Script generation": "해설문 생성",
        "LLM colloquial script": "LLM 구어체 해설문",
        "Narration per page": "페이지별 해설",
        "Guiding narrative": "내용을 이끄는 설명",
        "TTS synthesis": "TTS 합성",
        "Text → speech": "텍스트 → 음성",
        "Audio-video sync": "음성·영상 동기화",
        "ffmpeg synthesis": "ffmpeg 합성",
        "Match audio duration": "음성 길이에 맞춤",
        "Transition effects": "전환 효과",
        "Final video": "최종 동영상",
        "5-15 minutes": "5~15분",
        "Audio + visual output": "음성 + 시각 출력",
        "Acceptance criteria": "인수 기준",
        "10-20 pages · Cover main contributions · ≥3 original charts": "10~20장 · 핵심 기여 · 원본 차트 ≥3",
        "Rendering": "렌더링",
        "Zero text overflow · Reasonable layout · Text-image match": "넘침 없음 · 적절한 배치 · 그림 일치",
        "Video": "동영상",
        "5-15 minutes · Audio-video sync · Coherent narration": "5~15분 · 음성·영상 동기화 · 해설 일관",
    },
    "fig5-7.svg": {
        "① Log collection": "① 로그 수집",
        "   &quot;Cancel order #12345&quot;}": "   &quot;주문 #12345 취소&quot;}",
        "  → Agent did not inform user of the reason": "  → Agent가 사용자에게 이유를 알리지 않음",
        "② LLM analysis": "② LLM 분석",
        "Input: trace + architecture document + PRD": "입력: 궤적 + 아키텍처 문서 + PRD",
        "Analysis dimensions:": "분석 차원:",
        "  - Whether the execution flow meets expectations": "  - 실행 흐름이 기대에 맞는가",
        "  - Whether tool calls are correct": "  - 도구 호출이 올바른가",
        "  - Whether error handling is appropriate": "  - 오류 처리가 적절한가",
        "  - Whether user experience is satisfactory": "  - 사용자 경험이 만족스러운가",
        "→ Locate the deviating step and module": "→ 어긋난 단계와 모듈 찾기",
        "③ Structured report": "③ 구조화된 보고서",
        "Problem report:": "문제 보고서:",
        "  Priority: P1 (User Churn Risk)": "  우선순위: P1(사용자 이탈 위험)",
        "  Module: cancellation_handler": "  모듈: cancellation_handler",
        "  Description: After cancellation failure, no explanation of": "  설명: 취소 실패 후 사용자에게",
        "    the reason and alternatives is provided to the user": "    이유와 대안을 설명하지 않음",
        "  Suggestion: Add failure reason explanation": "  제안: 실패 이유 설명과",
        "    and guidance to purchase insurance": "    보험 가입 안내 추가",
        "④ Regression Test Case Generation": "④ 회귀 테스트 케이스 생성",
        "  &quot;&quot;&quot;Trajectory #001, Round 3-5&quot;&quot;&quot;": "  &quot;&quot;&quot;궤적 #001, 3~5차례&quot;&quot;&quot;",
        "  # Replay: User requests cancellation of economy class": "  # 재실행: 사용자가 이코노미 클래스 취소 요청",
        "    &quot;Cancel Order #12345&quot;)": "    &quot;주문 #12345 취소&quot;)",
        "  # Verify: Should explain the reason": "  # 검증: 이유를 설명해야 함",
        "  # Verify: Should not directly return an error": "  # 검증: 오류를 그대로 반환하면 안 됨",
        "⑤ GitHub Issue Auto-creation": "⑤ GitHub Issue 자동 생성",
        "  --title &quot;P1: Cancellation failure lacks": "  --title &quot;P1: 취소 실패 시",
        "    user guidance&quot; \\": "    사용자 안내 누락&quot; \\",
        "  --body &quot;**Problem**: Agent directly": "  --body &quot;**문제**: Agent가",
        "    returns an error after cancel_order": "    cancel_order 실패 후 오류를",
        "    failure, without explaining the reason...": "    그대로 반환하고 이유를 설명하지 않음...",
        "    **Trajectory**: #001 Round 3-5": "    **궤적**: #001 3~5차례",
        "    **Test**: test_cancel_...&quot; \\": "    **테스트**: test_cancel_...&quot; \\",
        "End-to-End Automation: Log → Analysis → Report → Test → Issue": "종단 간 자동화: 로그 → 분석 → 보고서 → 테스트 → Issue",
        "Integrate with GitHub via MCP · Test framework auto-replay verification": "MCP로 GitHub 연동 · 테스트 프레임워크 자동 재실행 검증",
        "Reduce manual diagnosis cost from hours to minutes": "사람의 진단 비용을 몇 시간에서 몇 분으로 단축",
    },
    "fig5-8.svg": {
        "User input": "사용자 입력",
        "&quot;I want to book a flight to Beijing&quot;": "&quot;베이징행 항공권 예약&quot;",
        "LLM analysis → Generate form code": "LLM 분석 → 양식 코드 생성",
        "  name=&quot;from&quot; label=&quot;Departure city&quot;/&gt;": "  name=&quot;from&quot; label=&quot;출발 도시&quot;/&gt;",
        "  name=&quot;depart&quot; label=&quot;Departure date&quot;/&gt;": "  name=&quot;depart&quot; label=&quot;출발일&quot;/&gt;",
        "  &lt;option&gt;One-way&lt;/option&gt;": "  &lt;option&gt;편도&lt;/option&gt;",
        "  &lt;option&gt;Round Trip&lt;/option&gt;": "  &lt;option&gt;왕복&lt;/option&gt;",
        "Rendered form interface": "렌더링된 양식 인터페이스",
        "Departure City": "출발 도시",
        "Shanghai": "상하이",
        "Departure Date": "출발일",
        "Trip Type": "여행 유형",
        "Round Trip ▾": "왕복 ▾",
        "Return Date": "귀국일",
        "Submit": "제출",
        "Structured JSON Response": "구조화된 JSON 응답",
        "{&quot;from&quot;: &quot;Shanghai&quot;,": "{&quot;from&quot;: &quot;상하이&quot;,",
        " &quot;type&quot;: &quot;Round Trip&quot;,": " &quot;type&quot;: &quot;왕복&quot;,",
        "Agent continues execution with complete parameters": "Agent가 완전한 매개변수로 작업 계속",
        "search_flights(from='Shanghai', to='Beijing', depart='2025-08-15', ...)": "search_flights(from='상하이', to='베이징', depart='2025-08-15', ...)",
        "Comparison: Plain Text vs Form": "비교: 일반 텍스트 vs 양식",
        "Text Q&amp;A: 10 rounds of dialogue": "텍스트 문답: 대화 10차례",
        "  Q1: Departure city? A: Shanghai": "  Q1: 출발 도시는? A: 상하이",
        "  Q2: Date? A: August 15": "  Q2: 날짜는? A: 8월 15일",
        "  Q3: One-way or round trip? ...": "  Q3: 편도인가, 왕복인가? ...",
        "Dynamic Form: 1 submission": "동적 양식: 한 번 제출",
        "  All information collected at once": "  모든 정보를 한 번에 수집",
        "  Cascading logic handled automatically": "  연쇄 로직 자동 처리",
        "Form code dynamically generated by LLM → Cascading logic: automatically show return date when &quot;Round Trip&quot; is selected": "LLM이 양식 코드를 생성 → &quot;왕복&quot; 선택 시 귀국일 자동 표시",
    },
    "fig5-9.svg": {
        "Traditional mode: data passes through LLM (inefficient)": "전통 방식: 데이터가 LLM을 거침(비효율적)",
        "✗ Inefficient": "✗ 비효율적",
        "User": "사용자",
        "&quot;Number of people per department?&quot;": "&quot;부서별 인원은?&quot;",
        "Generate SQL": "SQL 생성",
        "Execute ": "질의 ",
        " query": "실행",
        "Read ": "5,000행 ",
        " 5000 lines": "읽기",
        "Text ": "텍스트로 ",
        " description": "설명",
        "Problem: LLM copying data is error-prone · consumes many tokens · high latency": "문제: LLM의 데이터 전사 오류 · 많은 token 소비 · 높은 지연",
        "Artifact mode: data directly to frontend (efficient)": "산출물 방식: 데이터가 프런트엔드로 직행(효율적)",
        "✓ Efficient": "✓ 효율적",
        "LLM only generates code": "LLM은 코드만 생성",
        "Frontend executes directly": "프런트엔드가 직접 실행",
        "│ R&amp;D Dept │  42  │": "│ 연구개발부 │  42  │",
        "│ Marketing Dept │  28  │": "│ 마케팅부   │  28  │",
        "Visualization Artifact": "시각화 산출물",
        "Second artifact:": "두 번째 산출물:",
        "Data flow: DB → Frontend → Visualization (completely bypasses LLM)": "데이터 흐름: DB → 프런트엔드 → 시각화(LLM 완전 우회)",
        "LLM is only responsible for generating code, not for data transfer": "LLM은 코드 생성만 담당하며 데이터 전달에는 참여하지 않음",
    },
    "fig5-10.svg": {
        "Dust → Star": "먼지 → 별",
        "Physical Laws": "물리 법칙",
        "Star → Planet": "별 → 행성",
        "Gravitational aggregation": "중력에 의한 집합",
        "Planet → Life": "행성 → 생명",
        "DNA self-replication": "DNA 자기 복제",
        "Life → Agent": "생명 → Agent",
        "Code bootstrapping": "코드 부트스트래핑",
        "DNA self-replication: random mutation + natural selection": "DNA 자기 복제: 무작위 돌연변이 + 자연 선택",
        "Does not understand itself · Cannot modify directionally · 3.7 billion years of blind trial and error": "자기 이해 없음 · 의도적 수정 불가 · 37억 년의 시행착오",
        "Agent bootstrapping: understand code + directed design": "Agent 부트스트래핑: 코드 이해 + 의도적 설계",
        "Understands its own mechanisms · Creates purposefully · Inherits best practices": "자신의 메커니즘 이해 · 목적을 갖고 생성 · 모범 사례 상속",
        "Original Agent (own code)": "원본 Agent(자체 코드)",
        "System prompt": "시스템 프롬프트",
        "You are an airline customer service agent": "항공사 고객 서비스 Agent",
        "Cancellation rules: ...": "취소 규칙: ...",
        "Transfer rules: ...": "연결 규칙: ...",
        "Agent framework code": "Agent 프레임워크 코드",
        "Tool definition + MCP integration + message format": "도구 정의 + MCP 통합 + 메시지 형식",
        "Verified high-quality implementation": "검증된 고품질 구현",
        "Copy + modify": "복사 + 수정",
        "New Agent (after directed modification)": "새 Agent(의도적 수정 후)",
        "New system prompt": "새 시스템 프롬프트",
        "You are an e-commerce customer service agent": "전자 상거래 고객 서비스 Agent",
        "Refund rules: ...": "환불 규칙: ...",
        "Logistics inquiry: ...": "배송 조회: ...",
        "Inherited framework code": "상속한 프레임워크 코드",
        "New tools + new business logic": "새 도구 + 새 비즈니스 로직",
        "Architecture framework fully inherited → quality guaranteed": "아키텍처 프레임워크 완전 상속 → 품질 보장",
    },
    "fig5-11.svg": {
        "User requirements": "사용자 요구 사항",
        "&quot;Create an e-commerce refund customer service Agent&quot;": "&quot;전자 상거래 환불 Agent 생성&quot;",
        "Meta-Agent (Coding Agent)": "메타 Agent(Coding Agent)",
        "① Read reference code": "① 참조 코드 읽기",
        "→ Understand architecture patterns": "→ 아키텍처 패턴 이해",
        "② Copy scaffold": "② scaffold 복사",
        "Keep:": "유지:",
        "  Agent loop framework": "  Agent 루프 프레임워크",
        "  Message format / KV optimization": "  메시지 형식 / KV 최적화",
        "③ Targeted modifications": "③ 필요한 부분만 수정",
        "  → E-commerce refund rules": "  → 전자 상거래 환불 규칙",
        "  → Add refund tool": "  → 환불 도구 추가",
        "④ Verification testing": "④ 검증 테스트",
        "  → Start new Agent": "  → 새 Agent 시작",
        "  → Send test messages": "  → 테스트 메시지 전송",
        "  → Check tool calls": "  → 도구 호출 확인",
        "  → Verify conversation flow": "  → 대화 흐름 검증",
        "Generated new Agent": "생성된 새 Agent",
        "E-commerce refund rules": "전자 상거래 환불 규칙",
        "Refund / query tools": "환불 / 조회 도구",
        "Inherited framework code": "상속한 프레임워크 코드",
        "Model / parameter configuration": "모델 / 매개변수 설정",
        "Generated from scratch: lacks best practices": "처음부터 생성: 모범 사례 부족",
        "Ad-hoc context management · Non-standard tool design · Outdated API": "임시방편 컨텍스트 관리 · 비표준 도구 설계 · 낡은 API",
        "Modified from example: inherits best practices": "예시 기반 수정: 모범 사례 상속",
        "Standard message format · Standard tool design · Modern API": "표준 메시지 형식 · 표준 도구 설계 · 현대적 API",
    },
    "fig6-1.svg": {
        "Layer 1: Evaluate the Environment": "1계층: 평가 환경",
        '"Where to test" — Tool-calling / Human-computer interaction / Simulation environment': '"어디서 평가할까" — 도구 호출 / 인간-컴퓨터 상호작용 / 시뮬레이션 환경',
        "Layer 2: Evaluation Methods": "2계층: 평가 방법",
        '"How to judge" — Dataset design · LLM-as-a-Judge · Pairwise comparison and ranking': '"어떻게 판단할까" — 데이터셋 설계 · LLM-as-a-Judge · 쌍대 비교와 순위화',
        "Layer 3: Evaluation-Driven Decisions": "3계층: 평가 기반 의사결정",
        '"What to do after testing" — Model selection · Architecture optimization · Continuous iteration': '"평가 후 무엇을 할까" — 모델 선택 · 아키텍처 최적화 · 지속적 반복',
        "Engineering Themes Throughout the Chapter": "이 장을 관통하는 엔지니어링 주제",
        "• Observability": "• 관측 가능성",
        "• Simulation environment": "• 시뮬레이션 환경",
        "• Internal evaluation": "• 내부 평가",
    },
    "fig6-2.svg": {
        "Tool-calling type (Verifiers)": "도구 호출형(Verifiers)",
        "Agent (LLM)": "Agent(LLM)",
        "Tool execution environment": "도구 실행 환경",
        "Executable verifier": "실행형 검증기",
        "assert fib(10) == 55  # PASS": "assert fib(10) == 55  # 통과",
        "assert fib(0) == 0    # PASS": "assert fib(0) == 0    # 통과",
        "reward = 1.0 (all passed)": "reward = 1.0(모두 통과)",
        "Features: No human/LLM evaluation required": "특징: 사람/LLM 평가 불필요",
        "Human-computer interaction type (τ-bench)": "인간-컴퓨터 상호작용형(τ-bench)",
        "User simulator": "사용자 시뮬레이터",
        "&quot;My flight has a problem&quot;": "&quot;항공편에 문제가 있어요&quot;",
        "Tool call": "도구 호출",
        "→ {&quot;status&quot;:&quot;confirmed&quot;,&quot;flight&quot;:&quot;UA123&quot;}": "→ {&quot;status&quot;:&quot;확정&quot;,&quot;flight&quot;:&quot;UA123&quot;}",
        "Double verification": "이중 검증",
        "① DB: booking.status == &quot;cancelled&quot;": "① DB: booking.status == &quot;취소됨&quot;",
        "② Dialogue: contains &quot;refund $150&quot;": "② 대화: &quot;$150 환불&quot; 포함",
        "         contains &quot;3-5 business days to arrive&quot;": "         &quot;영업일 3~5일 내 입금&quot; 포함",
        "reward = 0/1 (both passed)": "reward = 0/1(둘 다 통과)",
        "Features: Progressive information disclosure + state verification": "특징: 점진적 정보 공개 + 상태 검증",
    },
    "fig6-3.svg": {
        "User Simulator (LLM)": "사용자 시뮬레이터(LLM)",
        "Known Information:": "알려진 정보:",
        "Name: Sarah Johnson": "이름: Sarah Johnson",
        "Booking: BK-98712": "예약: BK-98712",
        "Task Instruction:": "작업 지침:",
        '"There seems to be a problem with the flight"': '"항공편에 문제가 있는 것 같아요"',
        "→ Gradually reveal details": "→ 세부 정보를 점진적으로 공개",
        "→ Do not proactively provide the booking number": "→ 예약 번호를 먼저 알려 주지 않기",
        "Agent (To Be Evaluated)": "Agent(평가 대상)",
        "LLM Reasoning + Strategy Selection": "LLM 추론 + 전략 선택",
        "① May I have your booking number?": "① 예약 번호를 알려 주시겠어요?",
        "③ Flight UA123 has been canceled": "③ UA123 항공편이 취소됨",
        "⑤ Refund $150, 3-5 business days": "⑤ $150 환불, 영업일 3~5일",
        "Tools + Database": "도구 + 데이터베이스",
        "Query booking details": "예약 상세 조회",
        "Modify booking status": "예약 상태 변경",
        "Cancel and refund": "취소 및 환불",
        "Search for alternative flights": "대체 항공편 검색",
        "Send confirmation notification": "확인 알림 전송",
        "DB State:": "DB 상태:",
        "Dialogue": "대화",
        "Tool Call": "도구 호출",
        "Dual-control environment: User simulator can also directly operate the shared environment (tools + database)": "이중 제어 환경: 사용자 시뮬레이터도 공유 환경(도구 + 데이터베이스)을 직접 조작",
        "After task completion: Multi-layer verification": "작업 완료 후: 다계층 검증",
        "DB status check": "DB 상태 검사",
        "Dialogue content verification": "대화 내용 검증",
        "Contains 'refund' + amount": "'환불' + 금액 포함",
        "Contains 'arrival time'": "'입금 시점' 포함",
        "No false information present": "거짓 정보 없음",
        "Process compliance check": "절차 준수 검사",
        "Obtain user confirmation before modification": "변경 전 사용자 확인 받기",
        "No unauthorized operation": "무단 작업 없음",
        "No excessive transfer to human agent": "상담원에게 과도하게 이관하지 않음",
    },
    "fig6-4.svg": {
        "Rubric": "평가 기준표",
        "Factual Correctness: Essential": "사실 정확성: 필수",
        "Logical Coherence: Important": "논리적 일관성: 중요",
        "Hallucination Detection: Veto ⚠": "환각 탐지: 거부 ⚠",
        "Completeness: Important": "완전성: 중요",
        "Candidate Answer": "후보 답변",
        "Agent Output:": "Agent 출력:",
        "&quot;Refund processed, $150 will be credited within": "&quot;환불 처리 완료, $150가",
        " 3-5 business days.&quot;": " 영업일 3~5일 내 입금됩니다.&quot;",
        "Reference Solution (Optional)": "참고 답안(선택)",
        "Standard Answer / Scoring Points:": "표준 답안 / 채점 항목:",
        "Must include refund amount": "환불 금액을 포함해야 함",
        "Must include credit time": "입금 시점을 포함해야 함",
        "Cannot promise a specific date": "특정 날짜를 약속하면 안 됨",
        "Judge Model (GPT-5 / Gemini 2.5)": "평가 모델(GPT-5 / Gemini 2.5)",
        "Multi-source heterogeneous evaluation to prevent same-source bias": "동일 출처 편향을 막는 다중 출처 이종 평가",
        "Structured evaluation output": "구조화된 평가 출력",
        "Factual Correctness   ": "사실 정확성   ",
        "Amount and time are both accurate": "금액과 시점 모두 정확",
        "Completeness     ": "완전성     ",
        "Missing explanation of refund method": "환불 방식 설명 누락",
        "Hallucination Detection    ": "환각 탐지    ",
        "PASS": "통과",
        "No false information": "거짓 정보 없음",
        "Logical Coherence   ": "논리적 일관성   ",
        "Clear causal relationship": "인과관계가 명확함",
        "Scoring Aggregation Strategy": "점수 집계 전략",
        "Weighted average: Σ(weight × dimension score)": "가중 평균: Σ(가중치 × 차원 점수)",
        "Veto: Hallucination=FAIL → total score=0": "거부: 환각=실패 → 총점=0",
        "Multi-judge: median of 3 judges": "다중 평가: 평가 모델 3개의 중앙값",
        "Edge case flag: disagreement &gt;2 points → human review": "경계 사례 표시: 점수 차 &gt;2 → 사람 검토",
    },
    "fig6-5.svg": {
        "Chatbot Arena Anonymous Battle": "Chatbot Arena 익명 대결",
        "Model A (Anonymous)": "모델 A(익명)",
        "&quot;Refund processed, will arrive in 3-5": "&quot;환불 처리 완료, 영업일 3~5일 내",
        " business days to your account&quot;": " 계좌로 입금됩니다&quot;",
        "Model B (Anonymous)": "모델 B(익명)",
        "&quot;Okay, refund will be processed&quot;": "&quot;네, 환불이 처리됩니다&quot;",
        "VS": "대결",
        "User blind pick → A is better": "사용자 블라인드 선택 → A가 우수",
        "Elo Update Formula": "Elo 갱신 공식",
        "Expected win rate E_A = 1/(1+10^((R_B-R_A)/400))   |   Update: R_A' = R_A + K*(1-E_A)": "예상 승률 E_A = 1/(1+10^((R_B-R_A)/400))   |   갱신: R_A' = R_A + K*(1-E_A)",
        "Live Leaderboard (Example)": "실시간 순위표(예시)",
        "Rank": "순위",
        "Model": "모델",
        "Win rate vs #2": "2위 대비 승률",
        "GRPO: Introducing Pairwise Comparison into RL Training": "GRPO: RL 훈련에 쌍대 비교 도입",
        "A set of candidate responses → Normalize relative advantage → Policy update (bypass explicit reward model)": "후보 응답 집합 → 상대적 이점 정규화 → 정책 갱신(명시적 보상 모델 우회)",
    },
    "fig6-6.svg": {
        "Execution trace tree (single task)": "실행 궤적 트리(단일 작업)",
        "Trace: Check Beijing weather for user tomorrow (3.2s, $0.008)": "궤적: 사용자의 내일 베이징 날씨 조회(3.2초, $0.008)",
        "LLM Call: Intent recognition": "LLM 호출: 의도 인식",
        "Claude 4 Sonnet · 0.4s · 320 tokens": "Claude 4 Sonnet · 0.4초 · 320토큰",
        "Tool：get_weather(Beijing)": "도구: get_weather(Beijing)",
        "MCP Server · 1.8s · 200ms TTFT": "MCP 서버 · 1.8초 · 200ms TTFT",
        "├─ HTTP Request": "├─ HTTP 요청",
        "api.weather.com · 1.6s": "api.weather.com · 1.6초",
        "└─ Response Parse": "└─ 응답 파싱",
        "JSON → Structured weather data": "JSON → 구조화된 날씨 데이터",
        "LLM Call: Generate response": "LLM 호출: 응답 생성",
        "Claude 4 Sonnet · 0.8s · 580 tokens": "Claude 4 Sonnet · 0.8초 · 580토큰",
        "Tool：send_message(user)": "도구: send_message(user)",
        "0.2s · Contains weather summary": "0.2초 · 날씨 요약 포함",
        "Monitoring dashboard": "모니터링 대시보드",
        "Cost tracking": "비용 추적",
        "Today: $12.30 (1,200 calls)": "오늘: $12.30(1,200회 호출)",
        "This month: $340 (34K calls)": "이번 달: $340(34K회 호출)",
        "Anomaly: task#892 looped search 14 times, cost $2.1": "이상: task#892 검색 14회 반복, 비용 $2.1",
        "Performance monitoring": "성능 모니터링",
        "P50 / P95 / P99 latency: 2.1s / 8.4s / 15.2s": "P50 / P95 / P99 지연: 2.1초 / 8.4초 / 15.2초",
        "Tool success rate: 94.3%": "도구 성공률: 94.3%",
        "Quality audit": "품질 감사",
        "Task success rate: 87%    Hallucination trigger: 2.1%": "작업 성공률: 87%    환각 발생률: 2.1%",
        "Security violations: 0 (this month)    User satisfaction: 4.3/5": "보안 위반: 0건(이번 달)    사용자 만족도: 4.3/5",
        "Closed loop: Trace data → Identify issues → A/B testing → Prompt version management → Continuous optimization": "폐쇄 루프: 궤적 데이터 → 문제 식별 → A/B 테스트 → 프롬프트 버전 관리 → 지속적 최적화",
    },
    "fig6-7.svg": {
        "① Observation: Diagnostic Report": "① 관찰: 진단 보고서",
        "Overall Success Rate: 88% (102/116)": "전체 성공률: 88%(102/116)",
        "transcription: 0%  complex_ui: 17%": "transcription: 0%  complex_ui: 17%",
        "math_counting: 0%  Wi-Fi Operation: 0%": "math_counting: 0%  Wi-Fi 조작: 0%",
        "Task 82,102-115 Concentrated Failures": "작업 82, 102~115에 실패 집중",
        "② Hypothesis: Three-Layer Improvement Framework": "② 가설: 3계층 개선 프레임워크",
        "Surface Layer": "표면 계층",
        "H1 Set Navigation Prompt H2 UI Rules": "H1 탐색 프롬프트 설정 H2 UI 규칙",
        "Middle Layer": "중간 계층",
        "H3 Fix Multimodal Pipeline H4 Thinking": "H3 멀티모달 파이프라인 수정 H4 사고",
        "Deep Layer": "심층 계층",
        "H5 GPT-5 H6 UI Element Tree": "H5 GPT-5 H6 UI 요소 트리",
        "③ Experiment: Phased Validation (5 runs × 116 tasks per configuration)": "③ 실험: 단계별 검증(구성별 116개 작업 × 5회)",
        "H1 Navigation": "H1 탐색",
        "Setup 0%→75%": "설정 0%→75%",
        "token+8%": "토큰+8%",
        "H3 Multimodal": "H3 멀티모달",
        "Transcription 0%→80%": "전사 0%→80%",
        "Latency +1s": "지연 +1초",
        "H4 Thinking": "H4 사고",
        "Counting 0%→70%": "계수 0%→70%",
        "Latency 3x!": "지연 3배!",
        "H6 Element Tree": "H6 요소 트리",
        "token+30%": "토큰+30%",
        "④ Decision: Cost-Benefit Trade-off": "④ 결정: 비용-효과 절충",
        "✓ H1+H3: Low Cost, High Benefit → Deploy": "✓ H1+H3: 저비용, 고효과 → 배포",
        "✗ H4: Only 8% Tasks Benefit but 3x Latency → Reject": "✗ H4: 작업 8%만 개선, 지연 3배 → 기각",
        "✓ H6: 35% Improvement / 30% Cost → Deploy": "✓ H6: 35% 개선 / 비용 30% → 배포",
        "✗ H5: 15s/Step Unacceptable → Alternative": "✗ H5: 단계당 15초는 수용 불가 → 대안 모색",
        "⑤ Iteration: New Cycle": "⑤ 반복: 새 주기",
        "Deploy H1+H3+H6 → 88%→94%": "H1+H3+H6 배포 → 88%→94%",
        "New Report Shows Different Failure Modes:": "새 보고서에서 다른 실패 유형 발견:",
        "  H7: Conditional Thinking Enabled": "  H7: 조건부 사고 활성화",
        "  H8: Expand gesture action space": "  H8: 제스처 행동 공간 확장",
        "↑ Loop": "↑ 반복",
        "Methodology: Observe → Hypothesize → Experiment → Decide → Iterate = From alchemy to scientific engineering": "방법론: 관찰 → 가설 → 실험 → 결정 → 반복 = 연금술에서 과학적 엔지니어링으로",
    },
    "fig6-8.svg": {
        "Simulation fidelity →": "시뮬레이션 충실도 →",
        "Scalability": "확장성",
        "Mock API": "모의 API",
        "unit test level": "단위 테스트 수준",
        "million times/hour": "시간당 100만 회",
        "MCP sandbox": "MCP 샌드박스",
        "126 tool functions": "도구 함수 126개",
        "525s/round distributed": "라운드당 525초, 분산 실행",
        "Simulator": "시뮬레이터",
        "116 real-world application tasks": "실제 애플리케이션 작업 116개",
        "GPU parallelism": "GPU 병렬화",
        "thousands of parallel instances": "수천 개 인스턴스 병렬 실행",
        "Slightly compromised accuracy": "정확도 소폭 저하",
        "physics engine": "물리 엔진",
        "High-precision collision": "고정밀 충돌 처리",
        "Single-instance CPU": "단일 인스턴스 CPU",
        "real world": "현실 세계",
        "Perfect fidelity": "완벽한 충실도",
        "Non-resettable": "초기화 불가",
    },
    "fig6-9.svg": {
        "Multimodal observation": "멀티모달 관찰",
        "Head camera": "머리 카메라",
        "Left wrist camera": "왼쪽 손목 카메라",
        "Right wrist camera": "오른쪽 손목 카메라",
        "14-dimensional joint state vector": "14차원 관절 상태 벡터",
        "Vision-Language-Action model (VLA)": "시각-언어-행동 모델(VLA)",
        "Vision encoder": "시각 인코더",
        "SigLIP → visual tokens": "SigLIP → 시각 토큰",
        "Language model": "언어 모델",
        "Llama 2 7B backbone": "Llama 2 7B 백본",
        "Action decoder": "행동 디코더",
        "→ 14-dimensional continuous control vector": "→ 14차원 연속 제어 벡터",
        "Action chunking: generate 25 consecutive actions at once": "행동 청킹: 연속 행동 25개를 한 번에 생성",
        'Instruction: "Put the can into the pot"': '지시: "캔을 냄비에 넣으세요"',
        "SAPIEN physics engine": "SAPIEN 물리 엔진",
        "Dual-arm robot": "양팔 로봇",
        "7 DOF each = 14-dimensional action": "팔마다 7 DOF = 14차원 행동",
        "Environment randomization": "환경 무작위화",
        "Position 60cm / orientation ±22.5°": "위치 60cm / 방향 ±22.5°",
        "Collision detection + physics simulation": "충돌 탐지 + 물리 시뮬레이션",
        "Rigid body / soft body / friction": "강체 / 연체 / 마찰",
        "Action": "행동",
        "Observation": "관찰",
        "Evaluation metrics": "평가 지표",
        "Success rate": "성공률",
        "Can inside pot": "캔이 냄비 안에 있고",
        "and not fallen": "넘어지지 않음",
        "Completion time": "완료 시간",
        "25 steps × 25 actions": "25단계 × 행동 25개",
        "= 625 control steps": "= 제어 625단계",
        "Generalization ability": "일반화 능력",
        "Cross-position/orientation": "위치/방향 간",
        "/Appearance variant": "/외형 변형",
        "Sim-to-Real": "Sim-to-Real",
        "Domain randomization": "도메인 무작위화",
        "→ Real migration": "→ 현실로 전이",
    },
}


# These figures changed between the Chinese original and the English community
# translation.  Keep a complete, positional translation for the original text
# nodes so the Korean edition never inherits the English edition's geometry.
ORIGINAL_TEXTS = {
    "fig2-2.svg": [
        "요청(Agent 프레임워크 구성)",
        "system",
        "개발자가 작성한 규칙",
        "user",
        '"안녕하세요, 누구인가요?"',
        "호출",
        "응답(API 반환)",
        "assistant",
        "모델이 생성한 응답",
        '"안녕하세요! 저는 Coding Assistant입니다…"',
        "각 호출은 상태를 유지하지 않는다. 모델에 필요한 모든 정보는 요청의 messages 목록에 빠짐없이 제공해야 한다.",
    ],
    "fig2-3.svg": [
        "첫 번째 호출",
        "messages: system + user",
        "tools: get_current_time,",
        "get_weather",
        "API",
        "assistant: tool_calls",
        "get_current_time()  +",
        "get_weather()  (병렬)",
        "Agent 프레임워크가 두 도구를 병렬 실행",
        "두 번째 호출",
        "messages: + tool 결과",
        "밴쿠버 시각과 날씨",
        "메시지 기록에 추가",
        "API",
        "assistant: 최종 응답",
        "도구 호출 없음 → 루프 종료",
        '"현재 시각은…, 날씨는…"',
        "상태 비저장 API에서는 매 라운드마다 전체 메시지 기록을 모델에 다시 보내야 한다.",
    ],
    "fig2-4.svg": [
        "정적 접두부(매 라운드 동일)",
        "System Prompt(시스템 프롬프트)",
        "Tool Definitions(도구 정의)",
        "대화 기록 / 궤적(상호작용에 따라 계속 증가 →)",
        "user",
        "assistant",
        "tool 결과",
        "user",
        "…",
        "‘정적 접두부 + 궤적’ 구조: 접두부는 고정(KV Cache에 유리), 궤적은 압축 가능",
    ],
    "fig2-5.svg": [
        "사용자 요청",
        '“Xfinity 요금 협상”',
        "로컬 LLM 서비스",
        "vLLM/Ollama(OpenAI 호환)",
        "모델 추론",
        "판단 후 tool_call 생성",
        "로컬 도구 실행",
        "함수 / 외부 API 호출",
        "도구 결과를 모델에 반환해 최종 응답 생성",
    ],
    "fig2-6.svg": [
        "① ‘어때’가 앞선 각 단어에 부여한 어텐션 가중치",
        "베이징",
        "Key · 가중치 0.35",
        "의",
        "Key · 가중치 0.05",
        "날씨",
        "Key · 가중치 0.55",
        "어때",
        "Query(현재)",
        "Query와 각 Key의 점수 계산 → 가중치로 정규화 → Value의 가중합(‘날씨’를 중점 참고)",
        "② 어텐션 히트맵: 각 단어는 자신과 앞선 단어만 볼 수 있음(인과적 삼각형)",
        "Key →",
        "베이징",
        "의",
        "날씨",
        "어때",
        "Query ↓",
        "베이징",
        "1.00",
        "의",
        "0.30",
        "0.70",
        "날씨",
        "0.20",
        "0.10",
        "0.70",
        "어때",
        "0.35",
        "0.05",
        "0.55",
        "0.05",
        "칸이 진할수록 어텐션이 집중됨 · 위쪽 삼각형이 비어 있음 = 아직 생성되지 않은 단어는 볼 수 없음",
    ],
    "fig2-8.svg": [
        "구조화된 API 메시지",
        "system",
        '“You are a helpful assistant.”',
        "user",
        '“베이징은 오늘 날씨가 어때?”',
        "assistant",
        "(생성 대기)",
        "Chat Template",
        "모델이 실제로 처리하는 선형 Token 흐름",
        "<|im_start|>system",
        "You are a helpful assistant.<|im_end|>",
        "<|im_start|>user",
        "베이징은 오늘 날씨가 어때?<|im_end|>",
        "<|im_start|>assistant",
        "특수 토큰으로 역할과 메시지 경계를 구분해 하나의 연속된 시퀀스로 연결",
    ],
    "fig2-9.svg": [
        "API 계층(개발자에게 보이는 형태)",
        "{ ",
        '"role"',
        ": ",
        '"system"',
        ",",
        '"content"',
        ": ",
        '"AI 비서"',
        " }",
        "{ ",
        '"role"',
        ": ",
        '"user"',
        ",",
        '"content"',
        ": ",
        '"안녕"',
        " }",
        "모델 계층(Chat Template 변환 후)",
        "<|im_start|>",
        "system",
        "AI 비서",
        "<|im_end|>",
        "<|im_start|>",
        "user",
        "안녕",
        "<|im_end|>",
        "<|im_start|>",
        "assistant",
        "(모델이 여기서부터 생성)",
    ],
    "fig4-2.svg": [
        "주 Agent",
        "최소 전달",
        '"주문 번호 12345의 상태 조회"',
        "컨텍스트 없음 → 개인 정보 보호",
        "하위 Agent",
        "수동 선별 전달",
        '"사용자 지역: 미국',
        '요약: 환불 문의"',
        "명시적 선택 → 제어 가능",
        "하위 Agent",
        "자동 가지치기 전달",
        '"사용자 정보 + 최근 3턴',
        '+ 관련 도구 결과"',
        "규칙 기반 → 균형",
        "하위 Agent",
        "LLM 생성 컨텍스트",
        '"LLM이 궤적 분석',
        '→ 구조화된 컨텍스트 객체"',
        "가장 지능적 → 호출 1회 추가",
        "하위 Agent",
        "선택 가이드",
        "단순 고빈도 호출",
        "날씨 조회, 계산기",
        "→ 최소 전달",
        "중간 복잡도",
        "데이터 조회, 파일 처리",
        "→ 자동 가지치기",
        "복잡한 작업",
        "보고서 생성, 고객 서비스",
        "→ LLM 생성",
        "하위 Agent 컨텍스트 준비",
    ],
    "fig5-2.svg": [
        "① 프로젝트 문서화",
        "read_file",
        "README.md,",
        "ARCHITECTURE.md",
        "glob",
        "**/*.py, **/*.ts",
        "write_file",
        "→ CLAUDE.md 지침 생성",
        "② 요구 사항 이해",
        "ask_user",
        '"지연인가, 처리량인가?"',
        "grep",
        '"latency|throughput" src/',
        "read_file",
        "src/config.py(현 설정)",
        "③ 설계 문서",
        "write_file",
        "design.md(해법 비교)",
        "ask_user",
        "설계 제출 → 승인 대기",
        "—",
        "사람의 검토 후 → 계속",
        "④ Coding과 테스트",
        "edit_file",
        "old_str→new_str 코드 수정",
        "bash",
        "pytest tests/ -v",
        "edit_file",
        "실패한 테스트 수정 → 재실행",
        "⑤ 검토와 전달",
        "bash",
        "ruff check src/ (lint)",
        "read_file",
        "자기 검토: 가독성/보안/성능",
        "edit_file",
        "ARCHITECTURE.md 갱신",
        "폐쇄 루프 피드백 메커니즘",
        "테스트 실패 → 코드 수정 → 재테스트",
        "④ 내부 루프: 평균 2~3회에 수렴",
        "Lint 오류 → 즉시 수정 → 재검사",
        "⑤ 내부 루프: 편집 후 자동 실행",
        "검토에서 문제 발견 → ④로 돌아가 수정",
        "⑤→④ 되돌리기: 전달 품질 보장",
        "Agent 상태 표시줄: cwd, git 브랜치",
        "Agent 상태 표시줄: 스테이징 전 변경",
        "도구 출력: 앞뒤만 남기고 자르기",
        "영속 터미널 세션",
        "행동보다 계획 우선 · 전 과정 검증 · 문서와 코드의 공동 진화",
    ],
    "fig5-4.svg": [
        "Diff + Apply Model",
        "LLM 출력 Diff 설명:",
        "- def foo(x):",
        "    return x",
        "+ def foo(x, y=0):",
        "+   return x + y",
        "→ 소형 모델이 위치를 찾아 적용",
        "장점: 관심사 분리",
        "단점: 편차면 오배치",
        "이전 문자열 → 새 문자열",
        'old: "def foo(x):\\n',
        '       return x"',
        'new: "def foo(x, y=0):\\n',
        '       return x + y"',
        "→ 정확한 문자열 일치로 교체",
        "장점: 예측 가능",
        "단점: 삭제 원문 필요",
        "행 번호 지정",
        "42~43행을 지우고 삽입:",
        "  def foo(x, y=0):",
        "    return x + y",
        "",
        "→ 행 번호로 정확한 범위 지정",
        "장점: 큰 작업 효율",
        "단점: 행 번호 오류",
        "Vim식 명령",
        "42G  (42행으로 이동)",
        "cw   (단어 교체)",
        "dd   (행 삭제)",
        "yy/p (복사/붙여넣기)",
        "→ 풍부한 편집 의미",
        "장점: 재배치 효율",
        "단점: 약한 모델 오류",
        "시작-끝 일치",
        'start: "def foo(x):"',
        'end:   "    return x"',
        'new: "def foo(x, y=0):',
        '       return x + y"',
        "→ 경계만으로 위치를 찾음",
        "장점: 큰 삭제 편함",
        "단점: 고유 경계 필요",
        "실제 채택 사례",
        "Old→New",
        "Claude Code",
        "행 번호 지정",
        "IDE 깊은 통합 상황",
        "Diff + Apply",
        "Cursor",
        "시작-끝 일치",
        "일부 맞춤형 해법",
        "Vim 명령",
        "실험적 해법",
    ],
    "fig5-9.svg": [
        "전통 방식: 데이터가 LLM을 거침(비효율적)",
        "✗ 비효율적",
        "사용자",
        '"부서별',
        '인원은?"',
        "LLM",
        "SQL",
        "생성",
        "DB",
        "질의",
        "실행",
        "LLM",
        "5,000행",
        "읽기",
        "사용자",
        "텍스트로",
        "설명",
        "문제: LLM의 데이터 전사 오류 · 많은 token 소비 · 높은 지연",
        "산출물 방식: 데이터가 프런트엔드로 직행(효율적)",
        "✓ 효율적",
        "LLM은 코드만 생성",
        "build_artifact(",
        '  type="sql",',
        '  code="SELECT dept,',
        "    COUNT(*) as cnt",
        "    FROM employees",
        '    GROUP BY dept")',
        "프런트엔드가 직접 실행",
        "┌────────┬──────┐",
        "│ dept   │ cnt  │",
        "├────────┼──────┤",
        "│ 연구개발부 │  42  │",
        "│ 마케팅부   │  28  │",
        "└────────┴──────┘",
        "시각화 산출물",
        "두 번째 산출물:",
        "build_artifact(",
        '  type="chart",',
        '  code="bar(data)")',
        "데이터 흐름: DB → 프런트엔드 → 시각화(LLM 완전 우회)",
        "LLM은 코드 생성만 담당하며 데이터 전달에는 참여하지 않음",
        "SQL 결과 직접 전달",
    ],
}


TEXT_NODE_RE = re.compile(r"(<text\b[^>]*>)(.*?)(</text>)", re.DOTALL)

# Introduction and chapter 1 were localized before this script was added.  Their
# existing Korean text is authoritative; only transplant it onto the originals.
EXISTING_TEXT_ONLY = [
    "fig0-1.svg",
    "fig0-2.svg",
    "fig1-1.svg",
    "fig1-2.svg",
    "fig1-3.svg",
    "fig1-4.svg",
    "fig1-5.svg",
]

EXISTING_TEXT_REPLACEMENTS = {
    "fig1-5.svg": {
        "코드 검색 → 버그 식별 → 파일 수정 → 테스트 → 실패 수정 → 재수정 → 테스트 통과 → 완료":
            "검색 → 식별 → 수정 → 테스트 → 재수정 → 통과",
    },
}


def replace_text_node(svg: str, old: str, new: str, filename: str) -> str:
    needle = f">{old}</text>"
    count = svg.count(needle)
    if count == 0:
        raise ValueError(f"{filename}: text not found: {old!r}")
    return svg.replace(needle, f">{new}</text>")


def text_contents(svg: str) -> list[str]:
    return [match.group(2) for match in TEXT_NODE_RE.finditer(svg)]


def replace_text_contents(svg: str, translated: list[str], filename: str) -> str:
    matches = list(TEXT_NODE_RE.finditer(svg))
    if len(matches) != len(translated):
        raise ValueError(
            f"{filename}: original has {len(matches)} text nodes, "
            f"translation has {len(translated)}"
        )

    translated_iter = iter(translated)
    return TEXT_NODE_RE.sub(
        lambda match: match.group(1) + next(translated_iter) + match.group(3),
        svg,
    )


def main() -> None:
    for filename in EXISTING_TEXT_ONLY + list(TRANSLATIONS):
        original_svg = (ORIGINAL / filename).read_text(encoding="utf-8")

        if filename in ORIGINAL_TEXTS:
            translated_text = [
                html.escape(value, quote=False) for value in ORIGINAL_TEXTS[filename]
            ]
        elif filename in TRANSLATIONS:
            translations = TRANSLATIONS[filename]
            translation_source = (
                ORIGINAL if filename.startswith("fig3-") else ENGLISH
            ) / filename
            localized_svg = translation_source.read_text(encoding="utf-8")
            for old, new in translations.items():
                localized_svg = replace_text_node(localized_svg, old, new, filename)
            translated_text = text_contents(localized_svg)
        else:
            translated_text = text_contents(
                (DEST / filename).read_text(encoding="utf-8")
            )

        replacements = EXISTING_TEXT_REPLACEMENTS.get(filename, {})
        if replacements:
            translated_text = [
                html.escape(
                    replacements.get(html.unescape(value), html.unescape(value)),
                    quote=False,
                )
                for value in translated_text
            ]

        # Start from the Chinese original and alter text contents only.  All SVG
        # elements, coordinates, dimensions, colors, strokes, and font settings
        # therefore remain byte-for-byte identical to the original artwork.
        output = replace_text_contents(original_svg, translated_text, filename)
        (DEST / filename).write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
