#!/usr/bin/env python3
"""Translate chapter 2 SVG labels into Korean without changing their content."""

from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
DEST = ROOT / "book-ko" / "images"
ENGLISH = ROOT / "book-en" / "images"

KOREAN_FONT = "'Apple SD Gothic Neo', 'Malgun Gothic', Arial, sans-serif"
KOREAN_MONO_FONT = "'Apple SD Gothic Neo', 'Malgun Gothic', monospace"


TRANSLATIONS = {
    "fig2-1.svg": {
        "System Prompt": "시스템 프롬프트",
        "&quot;You are a helpful assistant. You MUST answer concisely.&quot;": "&quot;당신은 유용한 AI 비서입니다. 반드시 간결하게 답하세요.&quot;",
        "&quot;Use tools when the user asks for real-time information.&quot;": "&quot;사용자가 실시간 정보를 요청하면 도구를 사용하세요.&quot;",
        "Tool Definitions": "도구 정의",
        "{&quot;name&quot;: &quot;web_search&quot;, &quot;description&quot;: &quot;Search the web&quot;,": "{&quot;name&quot;: &quot;web_search&quot;, &quot;description&quot;: &quot;웹 검색&quot;,",
        "Conversation History": "대화 기록",
        "user: &quot;What's the weather in Beijing today?&quot;": "user: &quot;베이징은 오늘 날씨가 어때?&quot;",
        "assistant: [tool_call] → get_weather(&quot;Beijing&quot;)": "assistant: [tool_call] → get_weather(&quot;베이징&quot;)",
        "tool: {&quot;temp&quot;: &quot;23°C&quot;, &quot;conditions&quot;: &quot;clear&quot;}": "tool: {&quot;temp&quot;: &quot;23°C&quot;, &quot;conditions&quot;: &quot;맑음&quot;}",
        "Reasoning Trace": "생각 과정",
        "&lt;think&gt;The user asks about the weather. I already have the tool result,": "&lt;think&gt;사용자가 날씨를 물었고 도구 결과도 받았다.",
        "so I can directly summarize and respond without calling the tool again.&lt;/think&gt;": "도구를 다시 호출하지 않고 바로 요약해 답하면 된다.&lt;/think&gt;",
        "Current generation position →": "현재 생성 위치 →",
        "assistant: &quot;Beijing is clear today, temperature 23°C...&quot;  ← LLM is generating": "assistant: &quot;베이징은 오늘 맑고, 기온은 23°C입니다...&quot;  ← LLM 생성 중",
        "Context": "컨텍스트",
        "Window": "윈도",
        "Window size: Qwen3 = 32K tokens | Claude = 200K | Gemini = 2M": "윈도 크기: Qwen3 = 32K토큰 | Claude = 200K | Gemini = 2M",
        "All content serialized into token stream → processed by Transformer attention mechanism": "모든 내용을 토큰 스트림으로 직렬화 → Transformer 어텐션 처리",
    },
    "fig2-2.svg": {
        "Local Hardware": "로컬 하드웨어",
        "MLX Inference Backend": "MLX 추론 백엔드",
        "0.6B parameters · Q4 quantization": "매개변수 6억 개 · Q4 양자화",
        "&gt; 100 tokens/s": "초당 100토큰 이상",
        "ReAct + Tool calling capability": "ReAct + 도구 호출 역량",
        "Tool Registry": "도구 레지스트리",
        "ReAct Loop": "ReAct 루프",
        "user: &quot;What's the time and weather in Vancouver?&quot;": "user: &quot;밴쿠버의 현재 시각과 날씨는?&quot;",
        "Need to call get_current_time": "get_current_time과",
        "and get_temperature tools": "get_temperature 도구를 호출해야 함",
        "Continue loop": "루프 계속",
        "Final output:": "최종 출력:",
        "&quot;Vancouver: 05:18 AM, 13.2°C,": "&quot;밴쿠버: 오전 05:18, 13.2°C,",
        "  clear sky, humidity 93%&quot;": "  맑음, 습도 93%&quot;",
        "Streaming key timings": "스트리밍 핵심 시점",
        "&lt;think&gt;... → hidden, not shown to user": "&lt;think&gt;... → 숨김, 사용자에게 표시하지 않음",
        "plain text → real-time streaming display": "일반 텍스트 → 실시간 스트리밍 표시",
        "&lt;tool_call&gt; → parse and execute tool": "&lt;tool_call&gt; → 파싱 후 도구 실행",
    },
    "fig2-3.svg": {
        "# Tools": "# 도구",
        "You may call one or more functions...": "하나 이상의 함수를 호출할 수 있습니다...",
        "&quot;What's the weather like in Beijing today?&quot;": "&quot;베이징은 오늘 날씨가 어때?&quot;",
        "&lt;think&gt;Need to query weather, call get_weather tool&lt;/think&gt;": "&lt;think&gt;날씨 조회를 위해 get_weather 도구 호출&lt;/think&gt;",
        "&lt;tool_call&gt;{&quot;name&quot;:&quot;get_weather&quot;,&quot;args&quot;:{&quot;city&quot;:&quot;Beijing&quot;}}&lt;/tool_call&gt;": "&lt;tool_call&gt;{&quot;name&quot;:&quot;get_weather&quot;,&quot;args&quot;:{&quot;city&quot;:&quot;베이징&quot;}}&lt;/tool_call&gt;",
        "&lt;tool_response&gt;{&quot;temp&quot;:&quot;23°C&quot;,&quot;sky&quot;:&quot;clear&quot;}&lt;/tool_response&gt;": "&lt;tool_response&gt;{&quot;temp&quot;:&quot;23°C&quot;,&quot;sky&quot;:&quot;맑음&quot;}&lt;/tool_response&gt;",
        "← LLM starts generating new tokens from here": "← LLM이 여기서부터 새 토큰 생성",
        "special": "특수",
        "tokens": "토큰",
    },
    "fig2-4.svg": {
        "Request 1": "요청 1",
        "System Prompt + Tools (1200 tokens)": "시스템 프롬프트 + 도구(1,200토큰)",
        "user: &quot;How's the weather?&quot;": "user: &quot;날씨가 어때?&quot;",
        "→ generate response": "→ 답변 생성",
        "Request 2": "요청 2",
        "System Prompt + Tools (cache hit ✓)": "시스템 프롬프트 + 도구(캐시 적중 ✓)",
        "user: &quot;What time is it?&quot;": "user: &quot;지금 몇 시야?&quot;",
        "KV reuse": "KV 재사용",
        "Request 3": "요청 3",
        "(system prompt changed)": "(시스템 프롬프트 변경)",
        "System + Tools + &quot;Time: 10:30:45&quot;": "시스템 + 도구 + &quot;시각: 10:30:45&quot;",
        "→ full recomputation ✗": "→ 전체 재계산 ✗",
        "Performance Comparison (3000 token context)": "성능 비교(3,000토큰 컨텍스트)",
        "cache hit": "캐시 적중",
        "cache miss": "캐시 미적중",
        "~0.5 seconds": "약 0.5초",
        "3 - 5 seconds": "3~5초",
        "Cost": "비용",
        "only new tokens billed": "새 토큰만 과금",
        "all tokens rebilled": "전체 토큰 재과금",
    },
    "fig2-5.svg": {
        "No system prompt": "시스템 프롬프트 없음",
        "With system prompt": "시스템 프롬프트 있음",
        "System Prompt + Tools": "시스템 프롬프트 + 도구",
        "&quot;Help me contact Xfinity to negotiate&quot;": "&quot;Xfinity에 연락해 요금을 협상해 줘&quot;",
        "phone_call(Xfinity) → 1st attempt": "phone_call(Xfinity) → 1차 시도",
        "Result: waited 45 minutes, not connected": "결과: 45분 대기, 연결 실패",
        "web_search(&quot;Xfinity deals&quot;)": "web_search(&quot;Xfinity 할인&quot;)",
        "Result: [large amount of search content...]": "결과: [많은 검색 내용...]",
        "phone_call(Xfinity) → 2nd attempt": "phone_call(Xfinity) → 2차 시도",
        "Result: connected, quoted $65/month": "결과: 연결됨, 월 $65 제시",
        "phone_call(Xfinity) → 3rd attempt": "phone_call(Xfinity) → 3차 시도",
        "Result: confirmed price reduction to $59/month": "결과: 월 $59로 할인 확인",
        "&quot;Can you call again to follow up?&quot;": "&quot;한 번 더 전화해 확인해 줘&quot;",
        "→ Model needs to scan entire context to &quot;count&quot;": "→ 모델이 전체 컨텍스트를 훑어 호출 횟수를 세야 함",
        "number of calls made, prone to miscounting": "호출 횟수를 잘못 셀 가능성이 큼",
        "[ Same trajectory content ]": "[같은 궤적 내용]",
        "phone_call called 3 times (Xfinity: 3)": "phone_call 3회 호출(Xfinity: 3)",
        "Constraint check: limit reached (3/3) ✗": "제약 확인: 한도 도달(3/3) ✗",
        "TODO: [✓]Contact Xfinity [✓]Confirm price reduction": "TODO: [✓]Xfinity 연락 [✓]요금 할인 확인",
        "Current time: 2025-09-14 10:30": "현재 시각: 2025-09-14 10:30",
        "Current status: waiting for user confirmation": "현재 상태: 사용자 확인 대기",
        "→ Model directly reads refined status": "→ 모델이 정제된 상태를 바로 읽음",
        "Accurately follows constraints, no more calls": "제약을 정확히 지켜 더 전화하지 않음",
        "VS": "비교",
    },
    "fig2-6.svg": {
        "Strategy": "전략",
        "Tokens": "토큰",
        "Ratio": "비율",
        "Iters": "반복",
        "Result": "결과",
        "Token usage": "토큰 사용량",
        "No compression": "압축 없음",
        "5 (Failed)": "5(실패)",
        "✗ Failure": "✗ 실패",
        "Individual summary": "개별 요약",
        "✓ Success": "✓ 성공",
        "Combined summary": "통합 요약",
        "Context-aware": "컨텍스트 인식",
        "Aware + citation": "컨텍스트 인식 + 인용",
        "Adaptive window": "적응형 윈도",
        "Context-aware compression: 77% token reduction, highest success rate, fewest iterations": "컨텍스트 인식 압축: 토큰 77% 절감 · 가장 높은 성공률 · 가장 적은 반복 횟수",
        "Key: incorporate query intent and existing information into compression decisions": "핵심: 질의 의도와 기존 정보를 압축 판단에 함께 반영",
    },
    "fig2-8.svg": {
        "Layer 1: Metadata (loaded at startup, ~200 tokens)": "1계층: 메타데이터(시작할 때 로드, 약 200토큰)",
        "skills: [{name: &quot;PPTX&quot;, desc: &quot;Create PowerPoint presentations from content&quot;}": "skills: [{name: &quot;PPTX&quot;, desc: &quot;내용으로 PowerPoint 제작&quot;}",
        "        {name: &quot;PDF&quot;,  desc: &quot;Extract and analyze PDF documents&quot;}, ...]": "        {name: &quot;PDF&quot;,  desc: &quot;PDF 문서 추출 및 분석&quot;}, ...]",
        "Task trigger: &quot;Generate PPT from paper&quot;": "작업 트리거: &quot;논문으로 PPT 만들어 줘&quot;",
        "Layer 2: SKILL.md Core Flow (loaded on demand, ~2K tokens)": "2계층: SKILL.md 핵심 흐름(필요할 때 로드, 약 2K토큰)",
        "PPTX Skill Core Flow:": "PPTX Skill 핵심 흐름:",
        "1. markitdown extracts text → 2. Unzip PPTX to access XML": "1. markitdown으로 텍스트 추출 → 2. PPTX 압축을 풀어 XML 접근",
        "3. Modify slide{N}.xml content → 4. Repackage as .pptx": "3. slide{N}.xml 내용 수정 → 4. .pptx로 다시 압축",
        "References: → html2pptx.md | → reference.md | → scripts/": "참고 자료: → html2pptx.md | → reference.md | → scripts/",
        "Need detailed method: &quot;Create PPT using HTML template&quot;": "세부 방법 필요: &quot;HTML 템플릿으로 PPT 만들기&quot;",
        "Layer 3: Sub-documents (selective deep dive, loaded on demand)": "3계층: 하위 문서(필요한 자료만 선택적으로 로드)",
        "HTML template → PPT": "HTML 템플릿 → PPT",
        " complete workflow": " 전체 워크플로",
        "XML format specification": "XML 형식 명세와",
        " and technical details": " 기술 세부 사항",
        "Executable tools:": "실행 가능한 도구:",
        "thumbnail.py etc.": "thumbnail.py 등",
        "Fixed metadata → KV Cache friendly | Dynamic content appended → Cache not broken": "고정 메타데이터 → KV Cache에 유리 | 동적 내용은 끝에 추가 → 캐시 유지",
    },
    "fig2-9.svg": {
        "Original dialogue:": "원래 대화:",
        "&quot;I am a senior engineer at TechCorp, leading a team of 5 to build a recommendation system, using ML for three years&quot;": "&quot;저는 TechCorp의 선임 엔지니어로, 5명 팀을 이끌며 추천 시스템을 만들고 있고 ML 경력은 3년입니다&quot;",
        "Simple Notes": "단순 메모",
        "Atomic facts": "개별 사실",
        "&quot;User company: TechCorp&quot;": "&quot;사용자 회사: TechCorp&quot;",
        "&quot;User Position: Senior Engineer&quot;": "&quot;사용자 직급: 선임 엔지니어&quot;",
        "&quot;User Team: 5 people&quot;": "&quot;사용자 팀: 5명&quot;",
        "&quot;User Expertise: Recommendation System&quot;": "&quot;사용자 전문 분야: 추천 시스템&quot;",
        "Pros: O(1) operation,": "장점: O(1) 연산,",
        "extremely low overhead": "오버헤드가 매우 낮음",
        "Cons: Complete loss of": "단점: 연관성이",
        "relevance": "완전히 사라짐",
        "Enhanced Notes": "확장 메모",
        "Full Paragraph": "전체 문단",
        "&quot;Senior engineer at": "&quot;TechCorp의 선임 엔지니어,",
        "TechCorp, leads a team": "추천 시스템을 만드는",
        "of 5 building a rec.": "5명 팀을 이끌고 있으며",
        "system, 3 yrs in ML.&quot;": "ML 경력은 3년.&quot;",
        "Pros: Semantic": "장점: 의미적",
        "completeness": "완결성",
        "Cons: Redundancy +": "단점: 중복 +",
        "complex updates": "복잡한 갱신",
        "JSON Cards": "JSON 카드",
        "Hierarchical Structure": "계층 구조",
        "  company: &quot;TechCorp&quot;": "  company: &quot;TechCorp&quot;",
        "  title: &quot;Senior Engineer&quot;": "  title: &quot;선임 엔지니어&quot;",
        "Pros: Partial updates": "장점: 부분 갱신",
        "Cons: Rigid classification": "단점: 경직된 분류",
        "Adv. JSON Cards": "고급 JSON 카드",
        "Contextualized Knowledge": "맥락화된 지식",
        ' title: &quot;Senior Engineer&quot;,': ' title: &quot;선임 엔지니어&quot;,',
        ' backstory: &quot;Self-introduction&quot;,': ' backstory: &quot;자기소개&quot;,',
        "Pros: Disambiguation +": "장점: 모호성 해소 +",
        "traceability": "추적 가능성",
        "Cons: High generation cost": "단점: 높은 생성 비용",
        "Three-Level Evaluation Framework": "3단계 평가 체계",
        "Level 1: Basic Recall": "1단계: 기본 회상",
        "Store and retrieve direct information": "직접 정보를 저장하고 검색",
        "&quot;My membership number is 12345&quot; → Exact return": "&quot;내 회원 번호는 12345&quot; → 정확히 반환",
        "Level 2: Multi-session Retrieval": "2단계: 세션 간 검색",
        "Cross-session associative reasoning": "세션을 넘나드는 연관 추론",
        "&quot;Schedule maintenance for my car&quot; → Identify two cars": "&quot;내 차 정비를 예약해 줘&quot; → 차량 두 대 식별",
        "Level 3: Proactive Service": "3단계: 선제적 서비스",
        "Integrate multiple memories, anticipatory assistance": "여러 기억을 통합해 미리 지원",
        "Book international flight → Discover passport is about to expire": "국제선 예약 → 여권 만료가 임박했음을 발견",
    },
    "fig2-10.svg": {
        "Request 1": "요청 1",
        "System Prompt + Tools (1200 tokens)": "시스템 프롬프트 + 도구(1,200토큰)",
        "user: &quot;What's the weather like?&quot;": "user: &quot;오늘 날씨 어때?&quot;",
        "→ Generate response": "→ 답변 생성",
        "Request 2": "요청 2",
        "System Prompt + Tools (cache hit ✓)": "시스템 프롬프트 + 도구(캐시 적중 ✓)",
        "user: &quot;What time is it?&quot;": "user: &quot;지금 몇 시야?&quot;",
        "KV reuse": "KV 재사용",
        "Request 3": "요청 3",
        "(system prompt changed)": "(시스템 프롬프트 변경)",
        "System + Tools + &quot;Time: 10:30:45&quot;": "시스템 + 도구 + &quot;시각: 10:30:45&quot;",
        "→ Full recomputation ✗": "→ 전체 재계산 ✗",
        "Performance comparison (3000 token total context)": "성능 비교(전체 컨텍스트 3,000토큰)",
        "Cache hit": "캐시 적중",
        "Cache miss": "캐시 미적중",
        "~0.5 seconds": "약 0.5초",
        "3-5 seconds": "3~5초",
        "Cost": "비용",
        "New tokens only": "새 토큰만 과금",
        "All tokens rebilled": "전체 토큰 재과금",
    },
    "fig2-11.svg": {
        "Layer 1: Metadata (loaded at startup, ~300 tokens)": "1계층: 메타데이터(시작할 때 로드, 약 300토큰)",
        "skills: [{name: &quot;PPTX&quot;, desc: &quot;Create PowerPoint presentations from content&quot;}": "skills: [{name: &quot;PPTX&quot;, desc: &quot;내용으로 PowerPoint 제작&quot;}",
        "        {name: &quot;PDF&quot;,  desc: &quot;Extract and analyze PDF documents&quot;}, ...]": "        {name: &quot;PDF&quot;,  desc: &quot;PDF 문서 추출 및 분석&quot;}, ...]",
        "Task trigger: \"Generate PPT from paper\"": "작업 트리거: \"논문으로 PPT 만들어 줘\"",
        "Layer 2: SKILL.md core flow (loaded on demand, ~2K tokens)": "2계층: SKILL.md 핵심 흐름(필요할 때 로드, 약 2K토큰)",
        "PPTX Skill core flow:": "PPTX Skill 핵심 흐름:",
        "1. markitdown extract text → 2. Unzip PPTX to access XML": "1. markitdown으로 텍스트 추출 → 2. PPTX 압축을 풀어 XML 접근",
        "3. Modify slide{N}.xml content → 4. Repackage as .pptx": "3. slide{N}.xml 내용 수정 → 4. .pptx로 다시 압축",
        "References: → html2pptx.md | → reference.md | → scripts/": "참고 자료: → html2pptx.md | → reference.md | → scripts/",
        "Need detailed method: \"Create PPT with HTML template\"": "세부 방법 필요: \"HTML 템플릿으로 PPT 만들기\"",
        "Layer 3: Sub-documents (selective deep dive, loaded on demand)": "3계층: 하위 문서(필요한 자료만 선택적으로 로드)",
        "Complete workflow of": "전체 워크플로:",
        "HTML template → PPT": "HTML 템플릿 → PPT",
        "XML format specification": "XML 형식 명세와",
        "and technical details": "기술 세부 사항",
        "Executable tools:": "실행 가능한 도구:",
        "thumbnail.py etc.": "thumbnail.py 등",
        "Fixed metadata → KV Cache friendly | Dynamic content appended → Cache not invalidated": "고정 메타데이터 → KV Cache에 유리 | 동적 내용은 끝에 추가 → 캐시 유지",
    },
    "fig2-12.svg": {
        "{ role: \"system\", content: \"You are Claude Code assistant...\" }": "{ role: \"system\", content: \"당신은 Claude Code 비서입니다...\" }",
        "fixed": "고정",
        "{ role: \"user\", content: \"Help me generate a PPT from this PDF\" }": "{ role: \"user\", content: \"이 PDF로 PPT를 만들어 줘\" }",
        "     Available skills: pdf, pptx, ...&lt;/system-reminder&gt;\" }": "     사용 가능한 스킬: pdf, pptx, ...&lt;/system-reminder&gt;\" }",
        "ⓐ Skill listing": "ⓐ 스킬 목록",
        "Harness emit-once": "Harness가 한 번만 삽입",
        "~300 tokens": "약 300토큰",
        "{ role: \"tool\", content: \"Launching skill: pptx\" }   ← placeholder": "{ role: \"tool\", content: \"스킬 실행: pptx\" }   ← 자리표시자",
        "  content: \"Base directory: ...\\n# PPTX Skill": "  content: \"기준 디렉터리: ...\\n# PPTX Skill",
        "     ## Workflow: 1. Use markitdown...\" }": "     ## 워크플로: 1. markitdown 사용...\" }",
        "ⓑ Skill content": "ⓑ 스킬 내용",
        "Skill tool emit-once": "Skill 도구가 한 번만 삽입",
        "~2k tokens": "약 2K토큰",
        "{ role: \"tool\", content: \"...PDF text content...\" }": "{ role: \"tool\", content: \"...PDF 본문...\" }",
        "{ role: \"tool\", content: \"Wrote 12345 bytes\" }": "{ role: \"tool\", content: \"12,345바이트 작성 완료\" }",
        "Subsequent tool_use /": "이후 tool_use /",
        "tool_result continues": "tool_result가 끝에",
        "append to end": "계속 추가됨",
        "... subsequent rounds ...": "... 이후 라운드 ...",
        "ⓐ and ⓑ are both emit-once: after paying cache_creation once, they permanently reside in the cache prefix and will not move with subsequent tool_use": "ⓐ와 ⓑ는 한 번만 삽입된다. cache_creation 비용을 한 번 내면 캐시 접두부에 고정되고 이후 tool_use에도 위치가 바뀌지 않는다",
    },
    "fig2-13.svg": {
        "Turn 1 completed": "1턴 완료",
        "Turn 2 completed": "2턴 완료",
        "Turn 3 completed": "3턴 완료",
        "(first load PPTX skill)": "(PPTX 스킬 첫 로드)",
        "(read PDF file)": "(PDF 파일 읽기)",
        "(write HTML)": "(HTML 작성)",
        "NEW": "신규",
        "HIT": "적중",
        "★ skill_listing": "★ 스킬 목록",
        "★ skill_content": "★ 스킬 내용",
        "cache_creation for this turn": "이번 턴의 cache_creation",
        "≈ 2.5k tokens": "약 2.5K토큰",
        "≈ 0.5k tokens": "약 0.5K토큰",
        "≈ 0.4k tokens": "약 0.4K토큰",
        "NEW = new tokens added this turn, pay cache_creation once": "신규 = 이번 턴에 추가된 토큰, cache_creation 비용은 한 번만 지불",
        "HIT = already in cache prefix, free hit this turn": "적중 = 이미 캐시 접두부에 있어 이번 턴에는 무료로 재사용",
        "— content not yet generated this turn": "— 이번 턴에서 아직 생성되지 않은 내용",
        "★ Mark attachment with emit-once: pay cache_creation only on Turn 1,": "★ 한 번만 삽입하도록 표시: 1턴에서만 cache_creation 비용을 지불하고",
        "      then permanent HIT for all subsequent turns, marginal cost zero.": "      이후 모든 턴에서 계속 적중하므로 추가 비용은 0이다.",
        "Note: once inserted, the index position of each message never moves; new content is only appended to the end of the array.": "참고: 한 번 삽입된 메시지의 인덱스는 바뀌지 않으며 새 내용은 배열 끝에만 추가된다.",
    },
    "fig2-14.svg": {
        "No status bar": "상태 표시줄 없음",
        "With status bar": "상태 표시줄 있음",
        "System Prompt + Tools": "시스템 프롬프트 + 도구",
        "\"Help me contact Xfinity to negotiate\"": "\"Xfinity에 연락해 요금을 협상해 줘\"",
        "phone_call(Xfinity) → 1st attempt": "phone_call(Xfinity) → 1차 시도",
        "Result: waited 45 minutes, not connected": "결과: 45분 대기, 연결 실패",
        "web_search(&quot;Xfinity deals&quot;)": "web_search(&quot;Xfinity 할인&quot;)",
        "Result: [large amount of search content...]": "결과: [많은 검색 내용...]",
        "phone_call(Xfinity) → 2nd attempt": "phone_call(Xfinity) → 2차 시도",
        "Result: connected, quoted $65/month": "결과: 연결됨, 월 $65 제시",
        "phone_call(Xfinity) → 3rd attempt": "phone_call(Xfinity) → 3차 시도",
        "Result: confirmed price reduction to $59/month": "결과: 월 $59로 할인 확인",
        "\"Can you call again to follow up?\"": "\"한 번 더 전화해 확인해 줘\"",
        "→ Model needs to scan entire context to \"count\"": "→ 모델이 전체 컨텍스트를 훑어 호출 횟수를 세야 함",
        "how many calls were made, easy to miscount": "잘못 셀 가능성이 큼",
        "[ Same trajectory content ]": "[같은 궤적 내용]",
        "phone_call called 3 times (Xfinity: 3)": "phone_call 3회 호출(Xfinity: 3)",
        "Constraint check: reached limit (3/3) ✗": "제약 확인: 한도 도달(3/3) ✗",
        "TODO: [✓]Contact Xfinity [✓]Confirm price reduction": "TODO: [✓]Xfinity 연락 [✓]요금 할인 확인",
        "Current time: 2025-09-14 10:30": "현재 시각: 2025-09-14 10:30",
        "Current status: waiting for user confirmation": "현재 상태: 사용자 확인 대기",
        "→ Model directly reads the refined state": "→ 모델이 정제된 상태를 바로 읽음",
        "Accurately follows constraints, no more calls": "제약을 정확히 지켜 더 전화하지 않음",
        "VS": "비교",
    },
    "fig2-15.svg": {
        "{ role: \"system\", content: \"You are a telecom customer service agent...\" }": "{ role: \"system\", content: \"당신은 통신사 고객 서비스 Agent입니다...\" }",
        "fixed": "고정",
        "{ role: \"user\", content: \"Help me cancel my plan\" }": "{ role: \"user\", content: \"요금제를 해지해 줘\" }",
        "{ role: \"tool\", content: \"This plan has a contract period...\" }": "{ role: \"tool\", content: \"이 요금제에는 약정 기간이 있습니다...\" }",
        "{ role: \"assistant\", content: \"Your plan is within the contract period...\" }": "{ role: \"assistant\", content: \"현재 약정 기간 중입니다...\" }",
        "... more conversation turns ...": "... 더 많은 대화 턴 ...",
        "{ role: \"user\", content: \"Then help me check my call records\" }": "{ role: \"user\", content: \"그럼 통화 내역을 확인해 줘\" }",
        "user follow-up": "사용자 후속 요청",
        "  Called 3/3 times · TODO: Cancel plan (in progress)&lt;/agent_status&gt;\" }": "  전화 3/3회 · TODO: 요금제 해지(진행 중)&lt;/agent_status&gt;\" }",
        "Agent framework insertion": "Agent 프레임워크가 삽입한",
        "agent status bar": "Agent 상태 표시줄",
        "model starts generating from here": "모델이 여기서부터 생성",
        "← adjacent to model generation start, receives highest attention weight": "← 생성 시작점과 가까워 가장 높은 어텐션 가중치를 받음",
    },
    "fig2-16.svg": {
        "Strategy": "전략",
        "Tokens": "토큰",
        "Ratio": "비율",
        "Iters": "반복",
        "Result": "결과",
        "Token usage": "토큰 사용량",
        "No Compression": "압축 없음",
        "5 (Failed)": "5(실패)",
        "✗ Failed": "✗ 실패",
        "Individual Summary": "개별 요약",
        "✓ Success": "✓ 성공",
        "Combined Summary": "통합 요약",
        "Context-Aware": "컨텍스트 인식",
        "Awareness + Citation": "컨텍스트 인식 + 인용",
        "Adaptive Window": "적응형 윈도",
        "Context-Aware Compression: 77% token reduction, highest success rate, fewest iterations": "컨텍스트 인식 압축: 토큰 77% 절감 · 가장 높은 성공률 · 가장 적은 반복 횟수",
        "Key: Incorporate query intent and existing information into compression decisions": "핵심: 질의 의도와 기존 정보를 압축 판단에 함께 반영",
    },
    "fig2-17.svg": {
        "Each search returns ~70K characters → strategies handle it differently": "검색 1회당 약 7만 자 반환 → 전략마다 처리 방식이 다르다",
        "① No compression": "① 압축 없음",
        "Directly keep": "그대로 유지",
        "Full original text into context": "원문 전체를 컨텍스트에 삽입",
        "&gt; 110K tok → overflow": "&gt; 110K토큰 → 초과",
        "② Individual summary": "② 개별 요약",
        "Independent summary": "독립적으로 요약",
        "Each result independently generates 2-3 paragraph summaries": "각 결과를 따로 2~3개 문단으로 요약",
        "123K tok · 6.8%": "123K토큰 · 6.8%",
        "③ Combined summary": "③ 통합 요약",
        "Merged summary": "한꺼번에 요약",
        "All results concatenated then unified summary": "모든 결과를 합친 뒤 한 번에 요약",
        "55K tok · 2.1%": "55K토큰 · 2.1%",
        "④ Context-aware": "④ 컨텍스트 인식",
        "Intelligent compression": "질의 맞춤 압축",
        "Given query + context → targeted compression": "질의 + 컨텍스트를 반영해 필요한 내용만 압축",
        "25K tok · 0.9%": "25K토큰 · 0.9%",
        "⑤ Context-aware + citation": "⑤ 컨텍스트 인식 + 인용",
        "Intelligent + traceability": "맞춤 압축 + 추적 가능성",
        "Compressed content + retain URL citation markers": "내용은 압축하고 URL 인용 표시는 유지",
        "45K tok · 1.4%": "45K토큰 · 1.4%",
        "⑥ Adaptive window": "⑥ 적응형 윈도",
        "Deferred compression": "압축 시점 지연",
        "&lt; 80% window keep original text, batch compress when exceeded": "윈도 80% 미만이면 원문 유지, 넘으면 일괄 압축",
        "181K tok · maximum fidelity": "181K토큰 · 원문 충실도 최대",
    },
}


def replace_text_node(svg: str, old: str, new: str, filename: str) -> str:
    needle = f">{old}</text>"
    count = svg.count(needle)
    if count == 0:
        raise ValueError(f"{filename}: text not found: {old!r}")
    return svg.replace(needle, f">{new}</text>")


def main() -> None:
    for filename, translations in TRANSLATIONS.items():
        source = ENGLISH / filename
        svg = source.read_text(encoding="utf-8")
        for old, new in translations.items():
            svg = replace_text_node(svg, old, new, filename)

        svg = svg.replace(
            "Arial, 'Helvetica Neue', Helvetica, 'PingFang SC', 'Microsoft YaHei', sans-serif",
            KOREAN_FONT,
        )
        svg = svg.replace(
            "Arial,'Helvetica Neue',Helvetica,'PingFang SC','Microsoft YaHei',sans-serif",
            KOREAN_FONT,
        )
        svg = svg.replace("'Courier New', Courier, monospace", KOREAN_MONO_FONT)
        svg = svg.replace("'Courier New',Courier,monospace", KOREAN_MONO_FONT)

        (DEST / filename).write_text(svg, encoding="utf-8")


if __name__ == "__main__":
    main()
